/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payrollSystem.view;

import ik.ijse.payrollSystem.idgenerator.IDGenerator;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.payrollSystem.controller.LoansController;
import lk.ijse.payrollSystem.controller.SalaryController;
import lk.ijse.payrollSystem.dto.EmployeeDTO;
import lk.ijse.payrollSystem.dto.LevelDTO;
import lk.ijse.payrollSystem.dto.LoansDTO;
import lk.ijse.payrollSystem.dto.SalaryDTO;
import lk.ijse.payrollSystem.entity.Loans;
import lk.ijse.payrollSystem.validation.validation;

/**
 *
 * @author acer
 */
public class basicSalary extends javax.swing.JFrame {

    private SalaryController controller;
    private boolean update = false;

    /**
     * Creates new form basicSalary
     */
    public basicSalary() {
        controller = new SalaryController();
        initComponents();
        getAllEmployees();
        generatesalaryId();
        getAllLevels();
        setdate();
       // EmpIdcombobox.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Levellbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SalaryAmountlbl = new javax.swing.JLabel();
        SalaryTypelbl = new javax.swing.JLabel();
        Yearlbl = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        SalaryAomunttxt1 = new javax.swing.JTextField();
        monthly = new javax.swing.JRadioButton();
        yearly = new javax.swing.JRadioButton();
        daily = new javax.swing.JRadioButton();
        levelcombobox = new javax.swing.JComboBox<>();
        EmpIdlbl1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Deletelbl = new javax.swing.JLabel();
        Updatelbl = new javax.swing.JLabel();
        Savelbl = new javax.swing.JLabel();
        EmpIdcombobox = new com.jidesoft.swing.AutoCompletionComboBox();
        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JLabel();
        Employeetxt = new javax.swing.JLabel();
        loanbtn = new javax.swing.JLabel();
        paybtn = new javax.swing.JLabel();
        empbtn = new javax.swing.JLabel();
        attendancebtn = new javax.swing.JLabel();
        leavesReportBtn = new javax.swing.JLabel();
        loanreportBtn = new javax.swing.JLabel();
        paysheetbtn = new javax.swing.JLabel();
        leavesbtn = new javax.swing.JLabel();
        Employeetxt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Levellbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Levellbl.setForeground(new java.awt.Color(0, 102, 102));
        Levellbl.setText("Level");
        jPanel3.add(Levellbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 52, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        SalaryAmountlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SalaryAmountlbl.setText("Salary Amount");

        SalaryTypelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SalaryTypelbl.setText("Salary Type");

        Yearlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Yearlbl.setText("Date");

        datetxt.setEditable(false);
        datetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        SalaryAomunttxt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SalaryAomunttxt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        SalaryAomunttxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalaryAomunttxt1KeyTyped(evt);
            }
        });

        buttonGroup1.add(monthly);
        monthly.setText("Monthly");
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });

        buttonGroup1.add(yearly);
        yearly.setText("Yearly");
        yearly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlyActionPerformed(evt);
            }
        });

        buttonGroup1.add(daily);
        daily.setText("Daily");
        daily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalaryTypelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalaryAmountlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Yearlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(daily)
                        .addGap(38, 38, 38)
                        .addComponent(monthly)
                        .addGap(31, 31, 31)
                        .addComponent(yearly))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(datetxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SalaryAomunttxt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryTypelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthly)
                    .addComponent(yearly)
                    .addComponent(daily))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryAmountlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalaryAomunttxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Yearlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        levelcombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        levelcombobox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        levelcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                levelcomboboxItemStateChanged(evt);
            }
        });
        jPanel3.add(levelcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 250, 39));

        EmpIdlbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpIdlbl1.setForeground(new java.awt.Color(0, 102, 102));
        EmpIdlbl1.setText("Emp Name");
        jPanel3.add(EmpIdlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 111, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Basic Salary");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 400, 53));

        Deletelbl.setBackground(new java.awt.Color(0, 102, 102));
        Deletelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Deletelbl.setForeground(java.awt.Color.white);
        Deletelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deletelbl.setText("Delete");
        Deletelbl.setOpaque(true);
        Deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletelblMouseClicked(evt);
            }
        });
        jPanel3.add(Deletelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 750, 163, 40));

        Updatelbl.setBackground(new java.awt.Color(0, 102, 102));
        Updatelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Updatelbl.setForeground(java.awt.Color.white);
        Updatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Updatelbl.setText("Update");
        Updatelbl.setOpaque(true);
        Updatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatelblMouseClicked(evt);
            }
        });
        jPanel3.add(Updatelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 750, 163, 40));

        Savelbl.setBackground(new java.awt.Color(0, 102, 102));
        Savelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Savelbl.setForeground(java.awt.Color.white);
        Savelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Savelbl.setText("Add Salary");
        Savelbl.setOpaque(true);
        Savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavelblMouseClicked(evt);
            }
        });
        jPanel3.add(Savelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 750, 163, 40));

        EmpIdcombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpIdcombobox.setStrict(false);
        EmpIdcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EmpIdcomboboxItemStateChanged(evt);
            }
        });
        EmpIdcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIdcomboboxActionPerformed(evt);
            }
        });
        jPanel3.add(EmpIdcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 240, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(9, 9, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setBackground(new java.awt.Color(9, 9, 27));
        homebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/home2.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setOpaque(true);
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 286, 53));

        Employeetxt.setBackground(new java.awt.Color(9, 9, 27));
        Employeetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt.setText("Manage Employee");
        Employeetxt.setOpaque(true);
        Employeetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseExited(evt);
            }
        });
        jPanel1.add(Employeetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 286, 53));

        loanbtn.setBackground(new java.awt.Color(9, 9, 27));
        loanbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanbtn.setForeground(new java.awt.Color(255, 255, 255));
        loanbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanbtn.setText("Loan");
        loanbtn.setOpaque(true);
        loanbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loanbtnMouseDragged(evt);
            }
        });
        loanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanbtnMouseExited(evt);
            }
        });
        jPanel1.add(loanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 286, 53));

        paybtn.setBackground(new java.awt.Color(9, 9, 27));
        paybtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paybtn.setForeground(new java.awt.Color(255, 255, 255));
        paybtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paybtn.setText("PaySlip");
        paybtn.setOpaque(true);
        paybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paybtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paybtnMouseExited(evt);
            }
        });
        jPanel1.add(paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 286, 53));

        empbtn.setBackground(new java.awt.Color(9, 9, 27));
        empbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empbtn.setForeground(new java.awt.Color(255, 255, 255));
        empbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empbtn.setText("Employee Report");
        empbtn.setOpaque(true);
        empbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empbtnMouseExited(evt);
            }
        });
        jPanel1.add(empbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 286, 53));

        attendancebtn.setBackground(new java.awt.Color(9, 9, 27));
        attendancebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attendancebtn.setForeground(new java.awt.Color(255, 255, 255));
        attendancebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendancebtn.setText("Attendance");
        attendancebtn.setOpaque(true);
        attendancebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendancebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendancebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendancebtnMouseExited(evt);
            }
        });
        jPanel1.add(attendancebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 286, 53));

        leavesReportBtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesReportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesReportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesReportBtn.setText("Leaves Report");
        leavesReportBtn.setOpaque(true);
        leavesReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 290, 53));

        loanreportBtn.setBackground(new java.awt.Color(9, 9, 27));
        loanreportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanreportBtn.setForeground(new java.awt.Color(255, 255, 255));
        loanreportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanreportBtn.setText("Loans Report");
        loanreportBtn.setOpaque(true);
        loanreportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseExited(evt);
            }
        });
        jPanel1.add(loanreportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 53));

        paysheetbtn.setBackground(new java.awt.Color(9, 9, 27));
        paysheetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paysheetbtn.setForeground(new java.awt.Color(255, 255, 255));
        paysheetbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paysheetbtn.setText("Pay Sheet");
        paysheetbtn.setOpaque(true);
        paysheetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseExited(evt);
            }
        });
        jPanel1.add(paysheetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 286, 53));

        leavesbtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesbtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesbtn.setText("Leaves");
        leavesbtn.setOpaque(true);
        leavesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesbtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 286, 53));

        Employeetxt1.setBackground(new java.awt.Color(0, 102, 102));
        Employeetxt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt1.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt1.setText("Basic Salary");
        Employeetxt1.setOpaque(true);
        jPanel1.add(Employeetxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 286, 53));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void levelcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_levelcomboboxItemStateChanged
        try {
            String leId = (String) levelcombobox.getSelectedItem();
            LevelDTO level = controller.searchlevels(leId);
            if (level != null) {
                SalaryAomunttxt1.setText(level.getBasicSalary().toString());

            }
        } catch (Exception ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_levelcomboboxItemStateChanged

    private void SalaryAomunttxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalaryAomunttxt1KeyTyped
        validation.priceText(SalaryAomunttxt1);
    }//GEN-LAST:event_SalaryAomunttxt1KeyTyped

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyActionPerformed

    private void yearlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlyActionPerformed

    private void dailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyActionPerformed

    private void DeletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletelblMouseClicked

        try {
            boolean result = controller.deleteSalary((String) EmpIdcombobox.getSelectedItem());
            
            if (result) {
                JOptionPane.showMessageDialog(this, "Salary has been deleted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the salary");
            }
            clearTextFields();
            getAllEmployees();
        } catch (Exception ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeletelblMouseClicked

    private void SavelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavelblMouseClicked
             try {
        String salId = generatesalaryId();
        String Empname = (String) EmpIdcombobox.getSelectedItem();
        EmployeeDTO e=controller.searchEmployees(Empname);
        String level = (String) levelcombobox.getSelectedItem();
        String salaryType =null;
        if (daily.isSelected()) {
            salaryType="Daily";
        }else if(monthly.isSelected()){
            salaryType="Monthly";
        }else if(yearly.isSelected()){
            salaryType="Yearly";
        }
        BigDecimal salaryAmount = new BigDecimal(SalaryAomunttxt1.getText());
        String Date = datetxt.getText();
       
        SalaryDTO s=controller.searchSalary(Empname);
        if(s==null){
        SalaryDTO salary = new SalaryDTO(salId, e.geteId(), Empname, level, salaryType, salaryAmount, Date);

        if (!update) {
                boolean result = controller.saveSalary(salary);
                if (result) {
                    JOptionPane.showMessageDialog(this, "salary has been added successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the salary");
                }            
        }
        clearTextFields();
        generatesalaryId();
        }else{
            JOptionPane.showMessageDialog(this, "Already addded");
        }
        } catch (Exception ex) {
                Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_SavelblMouseClicked

    private void UpdatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatelblMouseClicked
        try {

            String salId =controller.searchSalaryId((String) EmpIdcombobox.getSelectedItem());
            String EmpId = (String) EmpIdcombobox.getSelectedItem();
            String Empname = (String) EmpIdcombobox.getSelectedItem();
        EmployeeDTO e=controller.searchEmployees(Empname);
            String level = (String) levelcombobox.getSelectedItem();
            String salaryType =null;
            if (daily.isSelected()) {
                salaryType="Daily";
            }else if(monthly.isSelected()){
                salaryType="Monthly";
            }else if(yearly.isSelected()){
                salaryType="Yearly";
            }
            BigDecimal salaryAmount = new BigDecimal(SalaryAomunttxt1.getText());
            String Date = datetxt.getText();

            SalaryDTO salary = new SalaryDTO(salId, e.geteId(), Empname, level, salaryType, salaryAmount, Date);

            boolean result = controller.updateSalary(salary);

            if (result) {
                JOptionPane.showMessageDialog(this, "Salary has been updated successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the salary");
            }
        } catch (Exception ex) {
            Logger.getLogger(level.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdatelblMouseClicked

    private void EmpIdcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EmpIdcomboboxItemStateChanged
       try {
            String eId = (String) EmpIdcombobox.getSelectedItem();
            EmployeeDTO employee = controller.searchEmployees(eId);
            if (employee != null) {
                levelcombobox.removeAllItems();
                //Empnametxt.setText(employee.getName());
             levelcombobox.addItem(employee.getLeId());
            }
        } catch (Exception ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmpIdcomboboxItemStateChanged

    private void EmpIdcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIdcomboboxActionPerformed
//        // TODO add your handling code here:
//        try {
//
//            String eId=(String) EmpIdcombobox.getSelectedItem();
//            EmployeeDTO employee=controller.searchEmployees(eId);
//
//            LoansDTO l=controller.getLoan(eId);
//
//            //SalaryDetailsDTO sd=controller.getSalaryDetail(eId);
//            if (employee != null) {
//
//                if (l != null) {
//
//                    Loantxt.setText(l.getTotal() + "");
//                }else{
//                    Loantxt.setText("0.00");
//                }
//                int i = 0;
//
//                LeavesDTO ld = controller.searchLeaves(employee.getName());
//
//                if (ld != null) {
//
//                    i = Integer.parseInt(ld.getBalanceLeave());
//
//                    if (i >= 0) {
//                        nopaytxt.setText("0.00");
//                    } else {
//                        double v = (i * -1) * 500;
//                        System.out.println(v);
//                        nopaytxt.setText(v + "");
//
//                    }
//                } else {
//                    nopaytxt.setText("0.00");
//                }
//                ////                    else{
//                    //                   Loantxt.setText("0.00");
//                    //               }
//                //               BigDecimal bd=sd.getNoPay();
//                //               double d=bd.doubleValue();
//                //               if(d>=0){
//                    //                    nopaytxt.setText("0.0");
//                    //               }else{
//                    //                   double v=(d*-1)*500;
//                    //                   nopaytxt.setText(v+"");
//                    //               }
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_EmpIdcomboboxActionPerformed

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnMouseClicked

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
        homebtn.setFont(new Font("Lucida Bright", 1, 30));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
        homebtn.setFont(new Font("Tahoma", 1, 18));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseExited

    private void loanbtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loanbtnMouseDragged

    private void loanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseClicked
        loan l = new loan();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanbtnMouseClicked

    private void loanbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseEntered
        loanbtn.setFont(new Font("Lucida Bright", 1, 30));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseEntered

    private void loanbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseExited
        loanbtn.setFont(new Font("Tahoma", 1, 18));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseExited

    private void paybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseClicked
        paySlip l = new paySlip();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paybtnMouseClicked

    private void paybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseEntered
        paybtn.setFont(new Font("Lucida Bright", 1, 30));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseEntered

    private void paybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseExited
        paybtn.setFont(new Font("Tahoma", 1, 18));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseExited

    private void empbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseClicked
        employeeReport e=new employeeReport();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empbtnMouseClicked

    private void empbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseEntered
        empbtn.setFont(new Font("Lucida Bright", 1, 30));
        empbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_empbtnMouseEntered

    private void empbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseExited
        empbtn.setFont(new Font("Thahoma",1,18));
        empbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_empbtnMouseExited

    private void attendancebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseClicked
        attendance p=new attendance();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendancebtnMouseClicked

    private void attendancebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseEntered
        attendancebtn.setFont(new Font("Lucida Bright", 1, 30));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseEntered

    private void attendancebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseExited
        attendancebtn.setFont(new Font("Tahoma", 1, 18));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseExited

    private void leavesReportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseClicked
        leavesReport l=new leavesReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesReportBtnMouseClicked

    private void leavesReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseEntered
        leavesReportBtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseEntered

    private void leavesReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseExited
        leavesReportBtn.setFont(new Font("Tahoma", 1, 18));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseExited

    private void loanreportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseClicked
        loanReport l = new loanReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanreportBtnMouseClicked

    private void loanreportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseEntered
        loanreportBtn.setFont(new Font("Lucida Bright", 1, 30));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseEntered

    private void loanreportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseExited
        loanreportBtn.setFont(new Font("Tahoma", 1, 18));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseExited

    private void paysheetbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseClicked
        paySheet p = new paySheet();
        p.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_paysheetbtnMouseClicked

    private void paysheetbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseEntered
        paysheetbtn.setFont(new Font("Lucida Bright", 1, 30));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseEntered

    private void paysheetbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseExited
        paysheetbtn.setFont(new Font("Tahoma", 1, 18));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseExited

    private void leavesbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseClicked
        leaves l = new leaves();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesbtnMouseClicked

    private void leavesbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseEntered
        leavesbtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseEntered

    private void leavesbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseExited
        leavesbtn.setFont(new Font("Tahoma", 1, 18));
        leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseExited

    private void EmployeetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseClicked
        ManageEmployee m = new ManageEmployee();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmployeetxtMouseClicked

    private void EmployeetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseEntered
         Employeetxt.setFont(new Font("Lucida Bright", 1, 30));
        Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseEntered

    private void EmployeetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseExited
       Employeetxt.setFont(new Font("Tahoma", 1, 18));
       Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basicSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basicSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basicSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basicSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basicSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deletelbl;
    private com.jidesoft.swing.AutoCompletionComboBox EmpIdcombobox;
    private javax.swing.JLabel EmpIdlbl1;
    private javax.swing.JLabel Employeetxt;
    private javax.swing.JLabel Employeetxt1;
    private javax.swing.JLabel Levellbl;
    private javax.swing.JLabel SalaryAmountlbl;
    private javax.swing.JTextField SalaryAomunttxt1;
    private javax.swing.JLabel SalaryTypelbl;
    private javax.swing.JLabel Savelbl;
    private javax.swing.JLabel Updatelbl;
    private javax.swing.JLabel Yearlbl;
    private javax.swing.JLabel attendancebtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton daily;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel empbtn;
    private javax.swing.JLabel homebtn;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel leavesReportBtn;
    private javax.swing.JLabel leavesbtn;
    private javax.swing.JComboBox<String> levelcombobox;
    private javax.swing.JLabel loanbtn;
    private javax.swing.JLabel loanreportBtn;
    private javax.swing.JRadioButton monthly;
    private javax.swing.JLabel paybtn;
    private javax.swing.JLabel paysheetbtn;
    private javax.swing.JRadioButton yearly;
    // End of variables declaration//GEN-END:variables

    private void getAllLevels() {
        try {
            ArrayList<String> allEmployees = controller.getEmployees();
            for (String employee : allEmployees) {
               
                EmpIdcombobox.addItem(employee);
            }
        } catch (Exception ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getAllEmployees() {
        try {
            ArrayList<String> allLeves = controller.getAllLeves();
            for (String level : allLeves) {
                levelcombobox.addItem(level);
            }
        } catch (Exception ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setdate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        datetxt.setText(sdf.format(date));
    }

    private void clearTextFields() {
        
       // Empnametxt.setText("");
        //SalaryTypetxt.setText("");
        SalaryAomunttxt1.setText("");

    }

    private String generatesalaryId() {
        String id=null;
        try {
           

         id= IDGenerator.getNewID("salary", "salId", "B");

        } catch (SQLException ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
}
