/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payrollSystem.view;

import ik.ijse.payrollSystem.idgenerator.IDGenerator;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import static java.lang.String.valueOf;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.payrollSystem.controller.LeavesController;
import lk.ijse.payrollSystem.dto.EmployeeDTO;
import lk.ijse.payrollSystem.dto.LeavesDTO;
import lk.ijse.payrollSystem.dto.LevelDTO;
import lk.ijse.payrollSystem.entity.Leaves;
import lk.ijse.payrollSystem.validation.validation;

/**
 *
 * @author acer
 */
public class leaves extends javax.swing.JFrame {

 
    private LeavesController controller;
    private boolean update = false;

    /**
     * Creates new form leaveEntry
     */
    public leaves() {
        controller = new LeavesController();
        initComponents();
        getAllEmployees();
        //getAllLevels();
        generateLeavesId();
        leaveIdtxt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        dateOfLeavestxt = new javax.swing.JTextField();
        calculatertxt = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        balanceleavetxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        monthtxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        totalleavestxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        updatelbl = new javax.swing.JLabel();
        savelbl = new javax.swing.JLabel();
        deletelbl = new javax.swing.JLabel();
        searchlbl = new javax.swing.JLabel();
        LevelCombobox = new javax.swing.JComboBox<>();
        LeaveTypetxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        leaveIdtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EmpIdcombobox = new com.jidesoft.swing.AutoCompletionComboBox();
        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JLabel();
        Employeetxt = new javax.swing.JLabel();
        loanbtn = new javax.swing.JLabel();
        paybtn = new javax.swing.JLabel();
        attendancebtn = new javax.swing.JLabel();
        leavesReportBtn = new javax.swing.JLabel();
        loanreportBtn = new javax.swing.JLabel();
        paysheetbtn = new javax.swing.JLabel();
        salarytxt = new javax.swing.JLabel();
        Employeetxt1 = new javax.swing.JLabel();
        Employeetxt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Emp Name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 26));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Level");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 52, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Leave Type");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 117, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Dates of leaves");

        dateOfLeavestxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateOfLeavestxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        dateOfLeavestxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateOfLeavestxtKeyTyped(evt);
            }
        });

        calculatertxt.setBackground(new java.awt.Color(255, 255, 255));
        calculatertxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculatertxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculatertxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/calcualter.png"))); // NOI18N
        calculatertxt.setText("Calculate  ");
        calculatertxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        calculatertxt.setOpaque(true);
        calculatertxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculatertxtMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Provide Leave");

        balanceleavetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceleavetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        balanceleavetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                balanceleavetxtKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Balance Leave");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Month");

        monthtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monthtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        monthtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthtxtActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Total leaves");

        totalleavestxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalleavestxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        totalleavestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalleavestxtActionPerformed(evt);
            }
        });
        totalleavestxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalleavestxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(calculatertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalleavestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(monthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateOfLeavestxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(balanceleavetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(monthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(totalleavestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dateOfLeavestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceleavetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(calculatertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        updatelbl.setBackground(new java.awt.Color(0, 102, 102));
        updatelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updatelbl.setForeground(java.awt.Color.white);
        updatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatelbl.setText("Update");
        updatelbl.setOpaque(true);
        updatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatelblMouseClicked(evt);
            }
        });

        savelbl.setBackground(new java.awt.Color(0, 102, 102));
        savelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savelbl.setForeground(java.awt.Color.white);
        savelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savelbl.setText("Save");
        savelbl.setOpaque(true);
        savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savelblMouseClicked(evt);
            }
        });

        deletelbl.setBackground(new java.awt.Color(0, 102, 102));
        deletelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletelbl.setForeground(java.awt.Color.white);
        deletelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletelbl.setText("Delete");
        deletelbl.setOpaque(true);
        deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletelblMouseClicked(evt);
            }
        });

        searchlbl.setBackground(new java.awt.Color(0, 102, 102));
        searchlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchlbl.setForeground(java.awt.Color.white);
        searchlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchlbl.setText("Search");
        searchlbl.setOpaque(true);
        searchlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(searchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(updatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 210, -1));

        LevelCombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LevelCombobox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LevelCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LevelComboboxItemStateChanged(evt);
            }
        });
        jPanel3.add(LevelCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 265, 36));

        LeaveTypetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LeaveTypetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        LeaveTypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveTypetxtActionPerformed(evt);
            }
        });
        jPanel3.add(LeaveTypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 265, 26));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Leave Id");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 97, -1));

        leaveIdtxt.setEditable(false);
        leaveIdtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        leaveIdtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        jPanel3.add(leaveIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 265, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Leaves");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 212, 53));

        EmpIdcombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpIdcombobox.setStrict(false);
        EmpIdcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EmpIdcomboboxItemStateChanged(evt);
            }
        });
        EmpIdcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIdcomboboxActionPerformed(evt);
            }
        });
        jPanel3.add(EmpIdcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 250, 40));

        jPanel1.setBackground(new java.awt.Color(9, 9, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setBackground(new java.awt.Color(9, 9, 27));
        homebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/home2.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setOpaque(true);
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 286, 53));

        Employeetxt.setBackground(new java.awt.Color(9, 9, 27));
        Employeetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt.setText("Manage Employee");
        Employeetxt.setOpaque(true);
        Employeetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseExited(evt);
            }
        });
        jPanel1.add(Employeetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 286, 53));

        loanbtn.setBackground(new java.awt.Color(9, 9, 27));
        loanbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanbtn.setForeground(new java.awt.Color(255, 255, 255));
        loanbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanbtn.setText("Loan");
        loanbtn.setOpaque(true);
        loanbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loanbtnMouseDragged(evt);
            }
        });
        loanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanbtnMouseExited(evt);
            }
        });
        jPanel1.add(loanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 286, 53));

        paybtn.setBackground(new java.awt.Color(9, 9, 27));
        paybtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paybtn.setForeground(new java.awt.Color(255, 255, 255));
        paybtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paybtn.setText("PaySlip");
        paybtn.setOpaque(true);
        paybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paybtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paybtnMouseExited(evt);
            }
        });
        jPanel1.add(paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 286, 53));

        attendancebtn.setBackground(new java.awt.Color(9, 9, 27));
        attendancebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attendancebtn.setForeground(new java.awt.Color(255, 255, 255));
        attendancebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendancebtn.setText("Attendance");
        attendancebtn.setOpaque(true);
        attendancebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendancebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendancebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendancebtnMouseExited(evt);
            }
        });
        jPanel1.add(attendancebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 286, 53));

        leavesReportBtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesReportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesReportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesReportBtn.setText("Leaves Report");
        leavesReportBtn.setOpaque(true);
        leavesReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 290, 53));

        loanreportBtn.setBackground(new java.awt.Color(9, 9, 27));
        loanreportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanreportBtn.setForeground(new java.awt.Color(255, 255, 255));
        loanreportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanreportBtn.setText("Loans Report");
        loanreportBtn.setOpaque(true);
        loanreportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseExited(evt);
            }
        });
        jPanel1.add(loanreportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 53));

        paysheetbtn.setBackground(new java.awt.Color(9, 9, 27));
        paysheetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paysheetbtn.setForeground(new java.awt.Color(255, 255, 255));
        paysheetbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paysheetbtn.setText("Pay Sheet");
        paysheetbtn.setOpaque(true);
        paysheetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseExited(evt);
            }
        });
        jPanel1.add(paysheetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 286, 53));

        salarytxt.setBackground(new java.awt.Color(9, 9, 27));
        salarytxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salarytxt.setForeground(new java.awt.Color(255, 255, 255));
        salarytxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salarytxt.setText("Basic Salary");
        salarytxt.setOpaque(true);
        salarytxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                salarytxtMouseDragged(evt);
            }
        });
        salarytxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salarytxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salarytxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salarytxtMouseExited(evt);
            }
        });
        jPanel1.add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 286, 53));

        Employeetxt1.setBackground(new java.awt.Color(0, 102, 102));
        Employeetxt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt1.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt1.setText("Leaves");
        Employeetxt1.setOpaque(true);
        jPanel1.add(Employeetxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 290, 53));

        Employeetxt2.setBackground(new java.awt.Color(9, 9, 27));
        Employeetxt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt2.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt2.setText("Employee Report");
        Employeetxt2.setOpaque(true);
        Employeetxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employeetxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Employeetxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Employeetxt2MouseExited(evt);
            }
        });
        jPanel1.add(Employeetxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 286, 53));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpIdcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIdcomboboxActionPerformed
        //        // TODO add your handling code here:
        //        try {
            //
            //            String eId=(String) EmpIdcombobox.getSelectedItem();
            //            EmployeeDTO employee=controller.searchEmployees(eId);
            //
            //            LoansDTO l=controller.getLoan(eId);
            //
            //            //SalaryDetailsDTO sd=controller.getSalaryDetail(eId);
            //            if (employee != null) {
                //
                //                if (l != null) {
                    //
                    //                    Loantxt.setText(l.getTotal() + "");
                    //                }else{
                    //                    Loantxt.setText("0.00");
                    //                }
                //                int i = 0;
                //
                //                LeavesDTO ld = controller.searchLeaves(employee.getName());
                //
                //                if (ld != null) {
                    //
                    //                    i = Integer.parseInt(ld.getBalanceLeave());
                    //
                    //                    if (i >= 0) {
                        //                        nopaytxt.setText("0.00");
                        //                    } else {
                        //                        double v = (i * -1) * 500;
                        //                        System.out.println(v);
                        //                        nopaytxt.setText(v + "");
                        //
                        //                    }
                    //                } else {
                    //                    nopaytxt.setText("0.00");
                    //                }
                //                ////                    else{
                    //                    //                   Loantxt.setText("0.00");
                    //                    //               }
                //                //               BigDecimal bd=sd.getNoPay();
                //                //               double d=bd.doubleValue();
                //                //               if(d>=0){
                    //                    //                    nopaytxt.setText("0.0");
                    //                    //               }else{
                    //                    //                   double v=(d*-1)*500;
                    //                    //                   nopaytxt.setText(v+"");
                    //                    //               }
                //            }
            //        } catch (Exception ex) {
            //            Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_EmpIdcomboboxActionPerformed

    private void EmpIdcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EmpIdcomboboxItemStateChanged
        try {
            String eId = (String) EmpIdcombobox.getSelectedItem();
            EmployeeDTO employee = controller.searchEmployees(eId);
            if (employee != null) {
                LevelCombobox.removeAllItems();
                //EmpNametxt.setText(employee.getName());
                LevelCombobox.addItem(employee.getLeId());

            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmpIdcomboboxItemStateChanged

    private void LeaveTypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveTypetxtActionPerformed
        monthtxt.requestFocus();
    }//GEN-LAST:event_LeaveTypetxtActionPerformed

    private void LevelComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LevelComboboxItemStateChanged
        try {
            String leId = (String) LevelCombobox.getSelectedItem();
            if(leId!=null){

                LevelDTO level = controller.searchlevels(leId);
                if (level != null) {
                    totalleavestxt.setText(level.getTotalLeaves());

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LevelComboboxItemStateChanged

    private void searchlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlblMouseClicked
        String Empname=EmpIdcombobox.getSelectedItem().toString();
        try {
            LeavesDTO searchLeaves;
            searchLeaves = controller.searchLeaves(Empname);
            if (searchLeaves != null) {
                //.setSelectedItem(searchLeaves.geteId());
                leaveIdtxt.setText(searchLeaves.getLevId());
                LevelCombobox.setSelectedItem(searchLeaves.getLevel());
                LeaveTypetxt.setText(searchLeaves.getType());
                monthtxt.setText(searchLeaves.getMonth());
                totalleavestxt.setText(searchLeaves.getTotalLeave());
                dateOfLeavestxt.setText(searchLeaves.getDatesOfLeaves());
                balanceleavetxt.setText(searchLeaves.getBalanceLeave());
            } else {
                JOptionPane.showMessageDialog(null, "No Employee");
            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchlblMouseClicked

    private void deletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletelblMouseClicked
        try {
            boolean result = controller.deleteLeaves(leaveIdtxt.getText());
            if (result) {
                JOptionPane.showMessageDialog(this, "Leaves has been deleted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the leaves");
            }
            clearTextFields();
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletelblMouseClicked

    private void savelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savelblMouseClicked
        try {
            String levId = leaveIdtxt.getText();
            String Empname = (String) EmpIdcombobox.getSelectedItem();
            EmployeeDTO emp=controller.searchEmployees(Empname);
            String level = (String) LevelCombobox.getSelectedItem();
            String leaveType = LeaveTypetxt.getText();
            String month = monthtxt.getText();
            String totalLeaves = totalleavestxt.getText();
            String datesOfLeaves = dateOfLeavestxt.getText();
            String balanceLeaves = balanceleavetxt.getText();

            LeavesDTO leaves = new LeavesDTO(levId, emp.geteId(), Empname, level, leaveType, month, totalLeaves, datesOfLeaves, balanceLeaves);

            if (!update) {

                boolean result = controller.saveLeaves(leaves);
                if (result) {
                    JOptionPane.showMessageDialog(this, "Leaves has been added successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the leaves");
                }

            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearTextFields();
        generateLeavesId();
    }//GEN-LAST:event_savelblMouseClicked

    private void updatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatelblMouseClicked
        try {
            String levId = leaveIdtxt.getText();
            String Empname = (String) EmpIdcombobox.getSelectedItem();
            EmployeeDTO e=controller.searchEmployees(Empname);
            // String Empname = EmpNametxt.getText();
            String level = (String) LevelCombobox.getSelectedItem();
            String leaveType = LeaveTypetxt.getText();
            String month = monthtxt.getText();
            String totalLeaves = totalleavestxt.getText();
            String datesOfLeaves = dateOfLeavestxt.getText();
            String balanceLeaves = balanceleavetxt.getText();

            System.out.println(levId);
            //System.out.println(EmpId);
            System.out.println(Empname);
            System.out.println(level);
            System.out.println(leaveType);
            System.out.println(month);
            System.out.println(totalLeaves);

            // System.out.println(datesOfLeaves);
            // System.out.println(balanceLeaves);

            LeavesDTO leaves=new LeavesDTO(levId,e.geteId(),Empname,level,leaveType,month,totalLeaves,datesOfLeaves,balanceLeaves);

            boolean result = controller.updateLeaves(leaves);

            if (result) {
                JOptionPane.showMessageDialog(this, "Leaves has been updated successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the leaves");
            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatelblMouseClicked

    private void totalleavestxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalleavestxtKeyTyped

    }//GEN-LAST:event_totalleavestxtKeyTyped

    private void totalleavestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalleavestxtActionPerformed
        dateOfLeavestxt.requestFocus();
    }//GEN-LAST:event_totalleavestxtActionPerformed

    private void monthtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthtxtActionPerformed
        totalleavestxt.requestFocus();
    }//GEN-LAST:event_monthtxtActionPerformed

    private void balanceleavetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balanceleavetxtKeyTyped

    }//GEN-LAST:event_balanceleavetxtKeyTyped

    private void calculatertxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatertxtMouseClicked
        int totalLeaves = Integer.parseInt(totalleavestxt.getText());
        int datesOfLeaves = Integer.parseInt(dateOfLeavestxt.getText());
        int balanceLeaves = totalLeaves - datesOfLeaves;
        String x = String.valueOf(balanceLeaves);
        balanceleavetxt.setText(x);
        if (balanceLeaves > 0) {

        }
    }//GEN-LAST:event_calculatertxtMouseClicked

    private void dateOfLeavestxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateOfLeavestxtKeyTyped

    }//GEN-LAST:event_dateOfLeavestxtKeyTyped

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnMouseClicked

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
        homebtn.setFont(new Font("Lucida Bright", 1, 30));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
        homebtn.setFont(new Font("Tahoma", 1, 18));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseExited

    private void EmployeetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseClicked
        ManageEmployee m = new ManageEmployee();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmployeetxtMouseClicked

    private void EmployeetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseEntered
        Employeetxt.setFont(new Font("Lucida Bright", 1, 30));
        Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseEntered

    private void EmployeetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseExited
        Employeetxt.setFont(new Font("Tahoma", 1, 18));
        Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseExited

    private void loanbtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loanbtnMouseDragged

    private void loanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseClicked
        loan l = new loan();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanbtnMouseClicked

    private void loanbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseEntered
        loanbtn.setFont(new Font("Lucida Bright", 1, 30));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseEntered

    private void loanbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseExited
        loanbtn.setFont(new Font("Tahoma", 1, 18));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseExited

    private void paybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseClicked
        paySlip l = new paySlip();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paybtnMouseClicked

    private void paybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseEntered
        paybtn.setFont(new Font("Lucida Bright", 1, 30));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseEntered

    private void paybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseExited
        paybtn.setFont(new Font("Tahoma", 1, 18));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseExited

    private void attendancebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseClicked
        attendance p=new attendance();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendancebtnMouseClicked

    private void attendancebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseEntered
        attendancebtn.setFont(new Font("Lucida Bright", 1, 30));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseEntered

    private void attendancebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseExited
        attendancebtn.setFont(new Font("Tahoma", 1, 18));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseExited

    private void leavesReportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseClicked
        leavesReport l=new leavesReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesReportBtnMouseClicked

    private void leavesReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseEntered
        leavesReportBtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseEntered

    private void leavesReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseExited
        leavesReportBtn.setFont(new Font("Tahoma", 1, 18));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseExited

    private void loanreportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseClicked
        loanReport l = new loanReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanreportBtnMouseClicked

    private void loanreportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseEntered
        loanreportBtn.setFont(new Font("Lucida Bright", 1, 30));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseEntered

    private void loanreportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseExited
        loanreportBtn.setFont(new Font("Tahoma", 1, 18));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseExited

    private void paysheetbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseClicked
        paySheet p = new paySheet();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paysheetbtnMouseClicked

    private void paysheetbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseEntered
        paysheetbtn.setFont(new Font("Lucida Bright", 1, 30));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseEntered

    private void paysheetbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseExited
        paysheetbtn.setFont(new Font("Tahoma", 1, 18));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseExited

    private void salarytxtMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_salarytxtMouseDragged

    private void salarytxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseClicked
        basicSalary b = new basicSalary();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salarytxtMouseClicked

    private void salarytxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseEntered
        salarytxt.setFont(new Font("Lucida Bright", 1, 30));
        salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseEntered

    private void salarytxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseExited
        salarytxt.setFont(new Font("Tahoma", 1, 18));
        salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseExited

    private void Employeetxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employeetxt2MouseClicked
        employeeReport e = new employeeReport();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Employeetxt2MouseClicked

    private void Employeetxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employeetxt2MouseEntered
      Employeetxt2.setFont(new Font("Lucida Bright", 1, 30));
      Employeetxt2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Employeetxt2MouseEntered

    private void Employeetxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employeetxt2MouseExited
      Employeetxt2.setFont(new Font("Tahoma", 1, 18));
      Employeetxt2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Employeetxt2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leaves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jidesoft.swing.AutoCompletionComboBox EmpIdcombobox;
    private javax.swing.JLabel Employeetxt;
    private javax.swing.JLabel Employeetxt1;
    private javax.swing.JLabel Employeetxt2;
    private javax.swing.JTextField LeaveTypetxt;
    private javax.swing.JComboBox<String> LevelCombobox;
    private javax.swing.JLabel attendancebtn;
    private javax.swing.JTextField balanceleavetxt;
    private javax.swing.JLabel calculatertxt;
    private javax.swing.JTextField dateOfLeavestxt;
    private javax.swing.JLabel deletelbl;
    private javax.swing.JLabel homebtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField leaveIdtxt;
    private javax.swing.JLabel leavesReportBtn;
    private javax.swing.JLabel loanbtn;
    private javax.swing.JLabel loanreportBtn;
    private javax.swing.JTextField monthtxt;
    private javax.swing.JLabel paybtn;
    private javax.swing.JLabel paysheetbtn;
    private javax.swing.JLabel salarytxt;
    private javax.swing.JLabel savelbl;
    private javax.swing.JLabel searchlbl;
    private javax.swing.JTextField totalleavestxt;
    private javax.swing.JLabel updatelbl;
    // End of variables declaration//GEN-END:variables

    private void getAllEmployees() {
        try {
            ArrayList<String> allEmployees = controller.getEmployees();
            for (String employee : allEmployees) {
                EmpIdcombobox.addItem(employee);
            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

  /* private void getAllLevels() {
        try {
            ArrayList<String> allLeves = controller.getAllLeves();
            for (String level : allLeves) {
                LevelCombobox.addItem(level);
            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/

    private void clearTextFields() {

       // EmpNametxt.setText("");
        LeaveTypetxt.setText("");
        monthtxt.setText("");
        totalleavestxt.setText("");
        dateOfLeavestxt.setText("");
        balanceleavetxt.setText("");
    }

    private void generateLeavesId() {
        try {
            leaveIdtxt.setText(IDGenerator.getNewID("Leaves", "levId", "V"));
        } catch (SQLException ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
