/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payrollSystem.view;

import com.jidesoft.swing.ComboBoxSearchable;
import ik.ijse.payrollSystem.idgenerator.IDGenerator;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.payrollSystem.controller.LoansController;
import lk.ijse.payrollSystem.dto.AttendanceDTO;
import lk.ijse.payrollSystem.dto.EmployeeDTO;
import lk.ijse.payrollSystem.dto.LevelDTO;
import lk.ijse.payrollSystem.dto.LoanCatagoryDTO;
import lk.ijse.payrollSystem.dto.LoansDTO;
import lk.ijse.payrollSystem.entity.Loans;
import lk.ijse.payrollSystem.validation.validation;


/**
 *
 * @author acer
 */
public class loan extends javax.swing.JFrame {
    private LoansController controller;
    private boolean update=false;
      private String levelId=null;
     private String empid=null;
     private String loanid=null;
     

    /**
     * Creates new form loan
     */
    public loan() {
        initComponents();
        controller =new LoansController();
        setDate();
        getAllEmployees();
        generateloanId();
       // getAllLevels();
        getAllLoanIds();
        getAllDue();
       getAllLoanDetails();
       ComboBoxSearchable searchable1=new ComboBoxSearchable(empCombo);
       empCombo.setEditable(true);
       
       loanTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(loanTable.getSelectedRow()== -1){
                    update=false;
                    clearTextFields();
                    return;
                
                }
                duecombobox.removeAllItems();
                totalLoanAmounttxt.setText(loanTable.getValueAt(loanTable.getSelectedRow(),2).toString());
                interesttxt.setText(loanTable.getValueAt(loanTable.getSelectedRow(),4).toString());
                duecombobox.addItem(loanTable.getValueAt(loanTable.getSelectedRow(),3).toString());
                update=true;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Datelbl = new javax.swing.JLabel();
        duelbl = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        duecombobox = new javax.swing.JComboBox<>();
        duelbl2 = new javax.swing.JLabel();
        totalLoanAmounttxt = new javax.swing.JTextField();
        Calculatelbl = new javax.swing.JLabel();
        Totaltxt = new javax.swing.JTextField();
        duelbl1 = new javax.swing.JLabel();
        interesttxt = new javax.swing.JTextField();
        LoanAmountlbl1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanTable = new javax.swing.JTable();
        LoanAmountlbl = new javax.swing.JLabel();
        Savelbl = new javax.swing.JLabel();
        Deletelbl = new javax.swing.JLabel();
        empCombo = new com.jidesoft.swing.AutoCompletionComboBox();
        LoanAmountlbl3 = new javax.swing.JLabel();
        levelIdText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JLabel();
        Employeetxt = new javax.swing.JLabel();
        paybtn = new javax.swing.JLabel();
        attendancebtn = new javax.swing.JLabel();
        loanreportBtn = new javax.swing.JLabel();
        paysheetbtn = new javax.swing.JLabel();
        leavesbtn = new javax.swing.JLabel();
        Employeetxt1 = new javax.swing.JLabel();
        salarytxt = new javax.swing.JLabel();
        Employeetxt2 = new javax.swing.JLabel();
        leavesReportBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Datelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Datelbl.setForeground(new java.awt.Color(0, 51, 51));
        Datelbl.setText("Date");
        jPanel5.add(Datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 107, 140, 34));

        duelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        duelbl.setForeground(new java.awt.Color(0, 51, 51));
        duelbl.setText("Interest");
        jPanel5.add(duelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 217, 140, 34));

        datetxt.setEditable(false);
        datetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(datetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 107, 242, 34));

        duecombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(duecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 169, 242, 35));

        duelbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        duelbl2.setText("Total");
        jPanel5.add(duelbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 276, 114, 34));

        totalLoanAmounttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLoanAmounttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalLoanAmounttxtKeyTyped(evt);
            }
        });
        jPanel5.add(totalLoanAmounttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 42, 242, 37));

        Calculatelbl.setBackground(new java.awt.Color(255, 255, 255));
        Calculatelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Calculatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calculatelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/calcualter.png"))); // NOI18N
        Calculatelbl.setText("Calculate  ");
        Calculatelbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        Calculatelbl.setOpaque(true);
        Calculatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatelblMouseClicked(evt);
            }
        });
        jPanel5.add(Calculatelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 206, 42));

        Totaltxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Totaltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotaltxtKeyTyped(evt);
            }
        });
        jPanel5.add(Totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 242, 34));

        duelbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        duelbl1.setForeground(new java.awt.Color(0, 51, 51));
        duelbl1.setText("due");
        jPanel5.add(duelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 169, 140, 34));

        interesttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel5.add(interesttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 225, 242, 33));

        LoanAmountlbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoanAmountlbl1.setForeground(new java.awt.Color(0, 51, 51));
        LoanAmountlbl1.setText("Total Loan Amount");
        jPanel5.add(LoanAmountlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 43, 181, 34));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 690, 370));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Loan");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 223, 53));

        loanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loan Category", "Loan Type", "Loan Amount", "Due", "Intrest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        loanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(loanTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 910, 230));

        LoanAmountlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoanAmountlbl.setForeground(new java.awt.Color(0, 51, 51));
        LoanAmountlbl.setText("Level");
        jPanel4.add(LoanAmountlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 34));

        Savelbl.setBackground(new java.awt.Color(0, 102, 102));
        Savelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Savelbl.setForeground(java.awt.Color.white);
        Savelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Savelbl.setText("Add Loans");
        Savelbl.setOpaque(true);
        Savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavelblMouseClicked(evt);
            }
        });
        jPanel4.add(Savelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 600, 163, 40));

        Deletelbl.setBackground(new java.awt.Color(0, 102, 102));
        Deletelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Deletelbl.setForeground(java.awt.Color.white);
        Deletelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deletelbl.setText("Delete");
        Deletelbl.setOpaque(true);
        Deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletelblMouseClicked(evt);
            }
        });
        jPanel4.add(Deletelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 740, 163, 40));

        empCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empCombo.setStrict(false);
        empCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                empComboItemStateChanged(evt);
            }
        });
        empCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empComboActionPerformed(evt);
            }
        });
        jPanel4.add(empCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 240, 40));

        LoanAmountlbl3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoanAmountlbl3.setForeground(new java.awt.Color(0, 51, 51));
        LoanAmountlbl3.setText("Emp Name");
        jPanel4.add(LoanAmountlbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, 34));

        levelIdText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        levelIdText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        levelIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelIdTextActionPerformed(evt);
            }
        });
        jPanel4.add(levelIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 229, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/Add_32px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 40, 45));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(9, 9, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setBackground(new java.awt.Color(9, 9, 27));
        homebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/home2.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setOpaque(true);
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 286, 53));

        Employeetxt.setBackground(new java.awt.Color(9, 9, 27));
        Employeetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt.setText("Manage Employee");
        Employeetxt.setOpaque(true);
        Employeetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseExited(evt);
            }
        });
        jPanel1.add(Employeetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 286, 53));

        paybtn.setBackground(new java.awt.Color(9, 9, 27));
        paybtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paybtn.setForeground(new java.awt.Color(255, 255, 255));
        paybtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paybtn.setText("PaySlip");
        paybtn.setOpaque(true);
        paybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paybtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paybtnMouseExited(evt);
            }
        });
        jPanel1.add(paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 286, 53));

        attendancebtn.setBackground(new java.awt.Color(9, 9, 27));
        attendancebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attendancebtn.setForeground(new java.awt.Color(255, 255, 255));
        attendancebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendancebtn.setText("Attendance");
        attendancebtn.setOpaque(true);
        attendancebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendancebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendancebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendancebtnMouseExited(evt);
            }
        });
        jPanel1.add(attendancebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 286, 53));

        loanreportBtn.setBackground(new java.awt.Color(9, 9, 27));
        loanreportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanreportBtn.setForeground(new java.awt.Color(255, 255, 255));
        loanreportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanreportBtn.setText("Loans Report");
        loanreportBtn.setOpaque(true);
        loanreportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseExited(evt);
            }
        });
        jPanel1.add(loanreportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 53));

        paysheetbtn.setBackground(new java.awt.Color(9, 9, 27));
        paysheetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paysheetbtn.setForeground(new java.awt.Color(255, 255, 255));
        paysheetbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paysheetbtn.setText("Pay Sheet");
        paysheetbtn.setOpaque(true);
        paysheetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseExited(evt);
            }
        });
        jPanel1.add(paysheetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 286, 53));

        leavesbtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesbtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesbtn.setText("Leaves");
        leavesbtn.setOpaque(true);
        leavesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesbtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 286, 53));

        Employeetxt1.setBackground(new java.awt.Color(0, 102, 102));
        Employeetxt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt1.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt1.setText("Loans");
        Employeetxt1.setOpaque(true);
        jPanel1.add(Employeetxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 53));

        salarytxt.setBackground(new java.awt.Color(9, 9, 27));
        salarytxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salarytxt.setForeground(new java.awt.Color(255, 255, 255));
        salarytxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salarytxt.setText("Basic Salary");
        salarytxt.setOpaque(true);
        salarytxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                salarytxtMouseDragged(evt);
            }
        });
        salarytxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salarytxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salarytxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salarytxtMouseExited(evt);
            }
        });
        jPanel1.add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 286, 53));

        Employeetxt2.setBackground(new java.awt.Color(9, 9, 27));
        Employeetxt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt2.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt2.setText("Employee Report");
        Employeetxt2.setOpaque(true);
        Employeetxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employeetxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Employeetxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Employeetxt2MouseExited(evt);
            }
        });
        jPanel1.add(Employeetxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 290, 53));

        leavesReportBtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesReportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesReportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesReportBtn.setText("Leaves Report");
        leavesReportBtn.setOpaque(true);
        leavesReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 290, 53));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        loanCatagory l = new loanCatagory();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void levelIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelIdTextActionPerformed

    private void empComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empComboActionPerformed

    private void empComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_empComboItemStateChanged
        try {
            // TODO add your handling code here:
            EmployeeDTO e=controller.searchEmployees(empCombo.getSelectedItem().toString());
            System.out.println(e.getLeId());
            LevelDTO l=controller.searchLevel(e.getLeId());

            if(l!=null)
            levelIdText.setText(e.getLeId());

        } catch (Exception ex) {
            Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_empComboItemStateChanged

    private void DeletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletelblMouseClicked
        try {
            boolean result=controller.deleteLoans((String) empCombo.getSelectedItem());
            if (result) {
                JOptionPane.showMessageDialog(this, "Loans has been deleted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the loans");
            }
            clearTextFields();
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DeletelblMouseClicked

    private void SavelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavelblMouseClicked
        String loanId=generateloanId();
         try {
        //    #String EmpId=(String) EmpIdcombobox3.getSelectedItem();
        String Empname=(String) empCombo.getSelectedItem();
        EmployeeDTO emp=controller.searchEmployees(Empname);
        String level=emp.getLeId();
        BigDecimal TotalLoanAmount=new BigDecimal(totalLoanAmounttxt.getText());
        String date=datetxt.getText();
        String due=(String) duecombobox.getSelectedItem();
        Double interest= Double.parseDouble(interesttxt.getText());
        BigDecimal total=new BigDecimal(Totaltxt.getText());
        LoansDTO l=controller.searchLoans(Empname);
        if(l==null){
        LoansDTO loans=new LoansDTO(loanId,emp.geteId(),Empname,level,TotalLoanAmount,date,due,interest,total);
               
        if (update) {
           
                boolean result = controller.saveLoans(loans);
                if (result) {
                    JOptionPane.showMessageDialog(this, "Loans has been added successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the loans");
                }
           
        }
        clearTextFields();
        }else{
            JOptionPane.showMessageDialog(this, "Already Added");
        }
         } catch (Exception ex) {
                Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_SavelblMouseClicked

    private void loanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTableMouseClicked

    private void TotaltxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotaltxtKeyTyped
        validation.priceText(Totaltxt);
    }//GEN-LAST:event_TotaltxtKeyTyped

    private void CalculatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatelblMouseClicked
        double totalLoanAmount =Double.parseDouble(totalLoanAmounttxt.getText());
        double due = Double.parseDouble(duecombobox.getSelectedItem().toString());
        double interest=Double.parseDouble(interesttxt.getText().toString());

        Double total= totalLoanAmount / due ;
        String x= String.valueOf(total*interest/100+total);
        Totaltxt.setText(x);

    }//GEN-LAST:event_CalculatelblMouseClicked

    private void totalLoanAmounttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalLoanAmounttxtKeyTyped
        validation.priceText(totalLoanAmounttxt);
    }//GEN-LAST:event_totalLoanAmounttxtKeyTyped

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnMouseClicked

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
        homebtn.setFont(new Font("Lucida Bright", 1, 30));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
        homebtn.setFont(new Font("Tahoma", 1, 18));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseExited

    private void EmployeetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseClicked
        ManageEmployee m = new ManageEmployee();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmployeetxtMouseClicked

    private void EmployeetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseEntered
        Employeetxt.setFont(new Font("Lucida Bright", 1, 30));
        Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseEntered

    private void EmployeetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseExited
        Employeetxt.setFont(new Font("Tahoma", 1, 18));
        Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseExited

    private void paybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseClicked
        paySlip l = new paySlip();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paybtnMouseClicked

    private void paybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseEntered
        paybtn.setFont(new Font("Lucida Bright", 1, 30));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseEntered

    private void paybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseExited
        paybtn.setFont(new Font("Tahoma", 1, 18));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseExited

    private void attendancebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseClicked
        attendance p=new attendance();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendancebtnMouseClicked

    private void attendancebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseEntered
        attendancebtn.setFont(new Font("Lucida Bright", 1, 30));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseEntered

    private void attendancebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseExited
        attendancebtn.setFont(new Font("Tahoma", 1, 18));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseExited

    private void loanreportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseClicked
        loanReport l = new loanReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanreportBtnMouseClicked

    private void loanreportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseEntered
        loanreportBtn.setFont(new Font("Lucida Bright", 1, 30));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseEntered

    private void loanreportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseExited
        loanreportBtn.setFont(new Font("Tahoma", 1, 18));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseExited

    private void paysheetbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseClicked
        paySheet p = new paySheet();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paysheetbtnMouseClicked

    private void paysheetbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseEntered
        paysheetbtn.setFont(new Font("Lucida Bright", 1, 30));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseEntered

    private void paysheetbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseExited
        paysheetbtn.setFont(new Font("Tahoma", 1, 18));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseExited

    private void leavesbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseClicked
        leaves l = new leaves();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesbtnMouseClicked

    private void leavesbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseEntered
        leavesbtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseEntered

    private void leavesbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseExited
        leavesbtn.setFont(new Font("Tahoma", 1, 18));
        leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseExited

    private void salarytxtMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_salarytxtMouseDragged

    private void salarytxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseClicked
        basicSalary b = new basicSalary();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salarytxtMouseClicked

    private void salarytxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseEntered
        salarytxt.setFont(new Font("Lucida Bright", 1, 30));
        salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseEntered

    private void salarytxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseExited
        salarytxt.setFont(new Font("Tahoma", 1, 18));
        salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseExited

    private void Employeetxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employeetxt2MouseClicked
        employeeReport e = new employeeReport();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Employeetxt2MouseClicked

    private void Employeetxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employeetxt2MouseEntered
        Employeetxt2.setFont(new Font("Lucida Bright", 1, 30));
        Employeetxt2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Employeetxt2MouseEntered

    private void Employeetxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employeetxt2MouseExited
        Employeetxt2.setFont(new Font("Tahoma", 1, 18));
        Employeetxt2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_Employeetxt2MouseExited

    private void leavesReportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseClicked
        leavesReport l=new leavesReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesReportBtnMouseClicked

    private void leavesReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseEntered
        leavesReportBtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseEntered

    private void leavesReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseExited
        leavesReportBtn.setFont(new Font("Tahoma", 1, 18));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseExited
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calculatelbl;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JLabel Deletelbl;
    private javax.swing.JLabel Employeetxt;
    private javax.swing.JLabel Employeetxt1;
    private javax.swing.JLabel Employeetxt2;
    private javax.swing.JLabel LoanAmountlbl;
    private javax.swing.JLabel LoanAmountlbl1;
    private javax.swing.JLabel LoanAmountlbl3;
    private javax.swing.JLabel Savelbl;
    private javax.swing.JTextField Totaltxt;
    private javax.swing.JLabel attendancebtn;
    private javax.swing.JTextField datetxt;
    private javax.swing.JComboBox<String> duecombobox;
    private javax.swing.JLabel duelbl;
    private javax.swing.JLabel duelbl1;
    private javax.swing.JLabel duelbl2;
    private com.jidesoft.swing.AutoCompletionComboBox empCombo;
    private javax.swing.JLabel homebtn;
    private javax.swing.JTextField interesttxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leavesReportBtn;
    private javax.swing.JLabel leavesbtn;
    private javax.swing.JTextField levelIdText;
    private javax.swing.JTable loanTable;
    private javax.swing.JLabel loanreportBtn;
    private javax.swing.JLabel paybtn;
    private javax.swing.JLabel paysheetbtn;
    private javax.swing.JLabel salarytxt;
    private javax.swing.JTextField totalLoanAmounttxt;
    // End of variables declaration//GEN-END:variables

    

    private void getAllEmployees() {
         try {
            ArrayList<String> allEmployees = controller.getEmployees();
            for (String employee : allEmployees) {
               empCombo.addItem(employee);
            }
        } catch (Exception ex) {
            Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void getAllLevels() {
         try {
            ArrayList<String> allLeves = controller.getAllLeves();
            for (String level : allLeves) {
               // Levelcombobox.addItem(level);
            }
        } catch (Exception ex) {
            Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void setDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        datetxt.setText(sdf.format(date));
    }

    private void getAllLoanIds() {
         try {
            ArrayList<String> allLoanIds = controller.getAllLoanIds();
            for (String LoanId : allLoanIds) {
             // loanidcombobox.addItem(LoanId);
            }
        } catch (Exception ex) {
            Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void getAllDue() {
         try {
            ArrayList<String> allDue = controller.getAllDues();
            for (String due : allDue) {
                duecombobox.addItem(due);
            }
        } catch (Exception ex) {
            Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearTextFields() {
        //EmpNametxt.setText("");
        totalLoanAmounttxt.setText("");
        interesttxt.setText ("");
        Totaltxt.setText("");
    }
    ArrayList<LoanCatagoryDTO> loans=new ArrayList<>();
    void getAllLoanDetails(){
        try {
            loans=controller.getAllLoanCategories();
            DefaultTableModel dtm = (DefaultTableModel) loanTable.getModel();
            dtm.setRowCount(0);
            
            for (LoanCatagoryDTO attendance : loans) {
                Object[] rowData = {
                    attendance.getLcId(),
                    attendance.getLoanType(),
                    attendance.getLoanAmount(),
                    attendance.getDue(),
                    attendance.getInterest()
                };
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private String generateloanId() {
        
        try {
           
         loanid= IDGenerator.getNewID("loans", "lId", "l");
            
        } catch (SQLException ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(basicSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        return loanid;
    }
}
