/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payrollSystem.view;

import ik.ijse.payrollSystem.idgenerator.IDGenerator;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.payrollSystem.controller.LoanCatagoryController;
import lk.ijse.payrollSystem.db.DBConnection;
import lk.ijse.payrollSystem.dto.LoanCatagoryDTO;
import lk.ijse.payrollSystem.validation.validation;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class loanCatagory extends javax.swing.JFrame {
     private LoanCatagoryController controller;
    private boolean update =false;

    /**
     * Creates new form loanCatagory
     */
    public loanCatagory() {
         controller= new LoanCatagoryController();
        initComponents();
        generateloanId();
        loantxt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        homebtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loanbtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LevelIdlbl = new javax.swing.JLabel();
        loantypetxt = new javax.swing.JTextField();
        LevelNamelbl = new javax.swing.JLabel();
        loanAmounttxt = new javax.swing.JTextField();
        BasicSalaryAmountlbl = new javax.swing.JLabel();
        BasicSalaryAmountlbl1 = new javax.swing.JLabel();
        interesttxt = new javax.swing.JTextField();
        BasicSalaryAmountlbl2 = new javax.swing.JLabel();
        duetxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Deletelbl = new javax.swing.JLabel();
        Updatelbl = new javax.swing.JLabel();
        Savelbl = new javax.swing.JLabel();
        Printlbl3 = new javax.swing.JLabel();
        loantxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(9, 9, 27));

        homebtn.setBackground(new java.awt.Color(9, 9, 27));
        homebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/home2.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setOpaque(true);
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Loan catagory");
        jLabel3.setOpaque(true);

        loanbtn.setBackground(new java.awt.Color(9, 9, 27));
        loanbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanbtn.setForeground(new java.awt.Color(255, 255, 255));
        loanbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanbtn.setText("Loan");
        loanbtn.setOpaque(true);
        loanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanbtnMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/loan.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Loan Catagory");
        jLabel6.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LevelIdlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LevelIdlbl.setForeground(new java.awt.Color(255, 255, 255));
        LevelIdlbl.setText("LoanId");
        jPanel4.add(LevelIdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 56, 90, -1));

        loantypetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loantypetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        loantypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loantypetxtActionPerformed(evt);
            }
        });
        jPanel4.add(loantypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 229, 26));

        LevelNamelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LevelNamelbl.setForeground(new java.awt.Color(0, 102, 102));
        LevelNamelbl.setText("Loan Type");
        jPanel4.add(LevelNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        loanAmounttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loanAmounttxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        loanAmounttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmounttxtActionPerformed(evt);
            }
        });
        loanAmounttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanAmounttxtKeyTyped(evt);
            }
        });
        jPanel4.add(loanAmounttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 229, 26));

        BasicSalaryAmountlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BasicSalaryAmountlbl.setForeground(new java.awt.Color(0, 102, 102));
        BasicSalaryAmountlbl.setText("Interest");
        jPanel4.add(BasicSalaryAmountlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 134, -1));

        BasicSalaryAmountlbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BasicSalaryAmountlbl1.setForeground(new java.awt.Color(0, 102, 102));
        BasicSalaryAmountlbl1.setText("Loan Amount");
        jPanel4.add(BasicSalaryAmountlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 134, -1));

        interesttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        interesttxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        interesttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                interesttxtKeyTyped(evt);
            }
        });
        jPanel4.add(interesttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 229, 26));

        BasicSalaryAmountlbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BasicSalaryAmountlbl2.setForeground(new java.awt.Color(0, 102, 102));
        BasicSalaryAmountlbl2.setText("Due ");
        jPanel4.add(BasicSalaryAmountlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 134, -1));

        duetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        duetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        duetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duetxtActionPerformed(evt);
            }
        });
        jPanel4.add(duetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 229, 26));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        Deletelbl.setBackground(new java.awt.Color(0, 102, 102));
        Deletelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Deletelbl.setForeground(new java.awt.Color(255, 255, 255));
        Deletelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deletelbl.setText("Delete");
        Deletelbl.setOpaque(true);
        Deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletelblMouseClicked(evt);
            }
        });

        Updatelbl.setBackground(new java.awt.Color(0, 102, 102));
        Updatelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Updatelbl.setForeground(new java.awt.Color(255, 255, 255));
        Updatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Updatelbl.setText("Update");
        Updatelbl.setOpaque(true);
        Updatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatelblMouseClicked(evt);
            }
        });

        Savelbl.setBackground(new java.awt.Color(0, 102, 102));
        Savelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Savelbl.setForeground(new java.awt.Color(255, 255, 255));
        Savelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Savelbl.setText("Save");
        Savelbl.setOpaque(true);
        Savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavelblMouseClicked(evt);
            }
        });

        Printlbl3.setBackground(new java.awt.Color(0, 102, 102));
        Printlbl3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Printlbl3.setForeground(new java.awt.Color(255, 255, 255));
        Printlbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Printlbl3.setText("Print");
        Printlbl3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Printlbl3.setOpaque(true);
        Printlbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Printlbl3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(Updatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(Deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Printlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Printlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        loantxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loantxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        loantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loantxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        home h=new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnMouseClicked

    private void loanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseClicked
       loan e=new loan();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanbtnMouseClicked

    private void SavelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavelblMouseClicked
   String loanId=loantxt.getText();
   String loanType=loantypetxt.getText();
        BigDecimal loanAmount= new BigDecimal(loanAmounttxt.getText());
        String due=duetxt.getText();
        Double interest=Double.parseDouble(interesttxt.getText());
        LoanCatagoryDTO loanCatagory=new LoanCatagoryDTO(loanId,loanType,loanAmount,due,interest);
        
          if (!update) {
            try {
                boolean result = controller.saveLoanCatagory(loanCatagory);
                if (result) {
                    JOptionPane.showMessageDialog(this, "loancatagory has been added successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the loancatagory");
                }
            } catch (Exception ex) {
                Logger.getLogger(loanCatagory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        clearTextFields();
         generateloanId(); 
        
     
    }//GEN-LAST:event_SavelblMouseClicked

    private void DeletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletelblMouseClicked
try {
            boolean result =controller.deleteLoanCatagory(loantxt.getText());
            
            
            if (result) {
                JOptionPane.showMessageDialog(this, "Loancatagory has been deleted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the Loancatagory");
            }
            clearTextFields();
        } catch (Exception ex) {
            Logger.getLogger(level.class.getName()).log(Level.SEVERE, null, ex);
        }      

    }//GEN-LAST:event_DeletelblMouseClicked

    private void UpdatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatelblMouseClicked
         try{   
        String loanId=loantxt.getText();
   String loanType=loantypetxt.getText();
        BigDecimal loanAmount= new BigDecimal(loanAmounttxt.getText());
        String due=duetxt.getText();
        Double interest=Double.parseDouble(interesttxt.getText());
        
             System.out.println(loanId);
             System.out.println(loanType);
             System.out.println(loanAmount);
             System.out.println(due);
             System.out.println(interest);
        
        
        
        LoanCatagoryDTO loanCatagory=new LoanCatagoryDTO(loanId,loanType,loanAmount,due,interest);
          boolean result = controller.updateLoanCatagory(loanCatagory);

        
            if (result) {
                    JOptionPane.showMessageDialog(this, "LoanCatagory has been updated successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update the loancatagory");
                }
            } catch (Exception ex) {
                Logger.getLogger(loanCatagory.class.getName()).log(Level.SEVERE, null, ex);
            }
           clearTextFields();
        
    }//GEN-LAST:event_UpdatelblMouseClicked

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
          homebtn.setFont(new Font("Lucida Bright", 1, 30));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
       homebtn.setFont(new Font("Tahoma", 1, 18));
       homebtn.setForeground(new Color(51, 255, 255));
    }//GEN-LAST:event_homebtnMouseExited

    private void loanbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseEntered
        loanbtn.setFont(new Font("Lucida Bright", 1, 30));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseEntered

    private void loanbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseExited
        loanbtn.setFont(new Font("Tahoma", 1, 18));
       loanbtn.setForeground(new Color(51, 255, 255));
    }//GEN-LAST:event_loanbtnMouseExited

    private void loanAmounttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanAmounttxtKeyTyped
        validation.priceText(loanAmounttxt);
    }//GEN-LAST:event_loanAmounttxtKeyTyped

    private void interesttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_interesttxtKeyTyped
    
    }//GEN-LAST:event_interesttxtKeyTyped

    private void loantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loantxtActionPerformed
      loantypetxt.requestFocus();
    }//GEN-LAST:event_loantxtActionPerformed

    private void loantypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loantypetxtActionPerformed
        loanAmounttxt.requestFocus();
    }//GEN-LAST:event_loantypetxtActionPerformed

    private void loanAmounttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmounttxtActionPerformed
        duetxt.requestFocus();
    }//GEN-LAST:event_loanAmounttxtActionPerformed

    private void duetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duetxtActionPerformed
       interesttxt.requestFocus();
    }//GEN-LAST:event_duetxtActionPerformed

    private void Printlbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Printlbl3MouseClicked
        try {
            InputStream is = getClass().getResourceAsStream("/lk/ijse/payrollSystem/reports/loan2.jasper");
            HashMap m = new HashMap();
            JasperPrint fillReport = JasperFillManager.fillReport(is, m, DBConnection.getInstance().getConnection());
            JasperViewer.viewReport(fillReport);
        } catch (Exception ex) {
            Logger.getLogger(employeeReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Printlbl3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanCatagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanCatagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanCatagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanCatagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanCatagory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BasicSalaryAmountlbl;
    private javax.swing.JLabel BasicSalaryAmountlbl1;
    private javax.swing.JLabel BasicSalaryAmountlbl2;
    private javax.swing.JLabel Deletelbl;
    private javax.swing.JLabel LevelIdlbl;
    private javax.swing.JLabel LevelNamelbl;
    private javax.swing.JLabel Printlbl3;
    private javax.swing.JLabel Savelbl;
    private javax.swing.JLabel Updatelbl;
    private javax.swing.JTextField duetxt;
    private javax.swing.JLabel homebtn;
    private javax.swing.JTextField interesttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField loanAmounttxt;
    private javax.swing.JLabel loanbtn;
    private javax.swing.JTextField loantxt;
    private javax.swing.JTextField loantypetxt;
    // End of variables declaration//GEN-END:variables

    private void clearTextFields() {
    loantxt.setText("");
    loantypetxt.setText("");
    loanAmounttxt.setText("");
    duetxt.setText("");
    interesttxt.setText("");

    }

    private void generateloanId() {
        try {
//             loantxt.setText(IDGenerator.getNewID("Loans","lId","C"));
             loantxt.setText(IDGenerator.getNewID("loancatagory","lcId","C"));
         } catch (SQLException ex) {
             Logger.getLogger(loanCatagory.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(loanCatagory.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(loanCatagory.class.getName()).log(Level.SEVERE, null, ex);
         }
         
    }
    
    
}
