/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payrollSystem.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import lk.ijse.payrollSystem.controller.UserController;
import lk.ijse.payrollSystem.dto.UserDTO;

/**
 *
 * @author acer
 */
public class LogingForm extends javax.swing.JFrame {

    /**
     * Creates new form loging
     */
    public LogingForm() {
        initComponents();
       // setTime();
        //setDate();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UserNamelbl = new javax.swing.JLabel();
        Passwordlbl = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Loginglbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        worninglbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Loging");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 40));

        UserNamelbl.setBackground(new java.awt.Color(9, 9, 27));
        UserNamelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserNamelbl.setForeground(new java.awt.Color(153, 153, 153));
        UserNamelbl.setText("UserName");
        jPanel1.add(UserNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 27));

        Passwordlbl.setBackground(new java.awt.Color(9, 9, 27));
        Passwordlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Passwordlbl.setForeground(new java.awt.Color(153, 153, 153));
        Passwordlbl.setText("Password");
        jPanel1.add(Passwordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 132, 25));

        userNameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userNameTxt.setForeground(new java.awt.Color(51, 51, 51));
        userNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 255)));
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 361, 40));

        PasswordTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasswordTxt.setForeground(new java.awt.Color(51, 51, 51));
        PasswordTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 204, 204)));
        PasswordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordTxtMouseClicked(evt);
            }
        });
        PasswordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 355, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/user.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 55, -1));

        Loginglbl.setBackground(new java.awt.Color(51, 51, 51));
        Loginglbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Loginglbl.setForeground(new java.awt.Color(255, 255, 255));
        Loginglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Loginglbl.setText("Loging");
        Loginglbl.setOpaque(true);
        Loginglbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginglblMouseClicked(evt);
            }
        });
        jPanel1.add(Loginglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 412, 290, 50));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cancel");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 550, 460));

        worninglbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        worninglbl.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(worninglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 414, 27));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
       PasswordTxt.requestFocus();
        
        
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void LoginglblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginglblMouseClicked
       try {
            String usernme = userNameTxt.getText();
            String password = new String(PasswordTxt.getPassword());
            
            UserDTO u = UserController.searche(usernme,password);
            if (usernme.equals(u.getUserName()) && password.equals(u.getPw())) {
                this.dispose();
                home mainPage = new home();
                mainPage.setVisible(true);
            } else {
                worninglbl.setText("Password or User Name doesn't match");
                userNameTxt.setText("");
                PasswordTxt.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(LogingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LoginglblMouseClicked

    private void PasswordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtActionPerformed
         userNameTxt.requestFocus();
    }//GEN-LAST:event_PasswordTxtActionPerformed

    private void PasswordTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTxtMouseClicked
        PasswordTxt.setText("");
        worninglbl.setText("");
    }//GEN-LAST:event_PasswordTxtMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loginglbl;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JLabel UserNamelbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JLabel worninglbl;
    // End of variables declaration//GEN-END:variables

 /*   private void setTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh-mm-ss a");
                timelbl.setText(sdf.format(date));
            }
        }).start();        }


    private void setDate() {
         Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        datelbl.setText(sdf.format(date));
       
    }*/
  
}