/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payrollSystem.view;

import ik.ijse.payrollSystem.idgenerator.IDGenerator;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.BOLD;
import java.io.IOException;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.text.StyleConstants.Bold;
import lk.ijse.payrollSystem.controller.ManageEmployeeController;
import lk.ijse.payrollSystem.dto.EmployeeDTO;
import lk.ijse.payrollSystem.dto.LevelDTO;
import lk.ijse.payrollSystem.validation.validation;

/**
 *
 * @author acer
 */
public class ManageEmployee extends javax.swing.JFrame {

    private boolean update = false;
    private ManageEmployeeController controller;

    /**
     * Creates new form SearchEmployee
     */
    public ManageEmployee() {
        
        initComponents();
        dateOfBirthcalender.setDateFormatString("yyyy-MM-dd");
        DateOfJoiningcalender.setDateFormatString("yyyy-MM-dd");
        controller = new ManageEmployeeController();
        getAllLevels();
        generateEmpId();
        EmpIdtxt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JLabel();
        Employeetxt = new javax.swing.JLabel();
        loanbtn = new javax.swing.JLabel();
        salarytxt = new javax.swing.JLabel();
        paybtn = new javax.swing.JLabel();
        empbtn = new javax.swing.JLabel();
        attendancebtn = new javax.swing.JLabel();
        leavesReportBtn = new javax.swing.JLabel();
        loanreportBtn = new javax.swing.JLabel();
        paysheetbtn = new javax.swing.JLabel();
        leavesbtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EmpNamelbl = new javax.swing.JLabel();
        EmpNametxt = new javax.swing.JTextField();
        NIClbl = new javax.swing.JLabel();
        NICtxt = new javax.swing.JTextField();
        Genderlbl = new javax.swing.JLabel();
        Maleradiobtn = new javax.swing.JRadioButton();
        Femaleradiobtn = new javax.swing.JRadioButton();
        DateOfBirthlbl = new javax.swing.JLabel();
        Addresslbl = new javax.swing.JLabel();
        Levellbl = new javax.swing.JLabel();
        TelNolbl = new javax.swing.JLabel();
        DateOfJoininglbl = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JTextField();
        dateOfBirthcalender = new com.toedter.calendar.JDateChooser();
        DateOfJoiningcalender = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Addresstxtarea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        Savelbl = new javax.swing.JLabel();
        Deletelbl = new javax.swing.JLabel();
        Updatelbl = new javax.swing.JLabel();
        Searchlbl = new javax.swing.JLabel();
        TelNotxt = new javax.swing.JTextField();
        Emaillbl = new javax.swing.JLabel();
        Levelcombobox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        EmpIdtxt = new javax.swing.JTextField();
        EmpIdlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 9, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setBackground(new java.awt.Color(9, 9, 27));
        homebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/home2.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setOpaque(true);
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 286, 53));

        Employeetxt.setBackground(new java.awt.Color(0, 102, 102));
        Employeetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt.setText("Manage Employee");
        Employeetxt.setOpaque(true);
        jPanel1.add(Employeetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 286, 53));

        loanbtn.setBackground(new java.awt.Color(9, 9, 27));
        loanbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanbtn.setForeground(new java.awt.Color(255, 255, 255));
        loanbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanbtn.setText("Loan");
        loanbtn.setOpaque(true);
        loanbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loanbtnMouseDragged(evt);
            }
        });
        loanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanbtnMouseExited(evt);
            }
        });
        jPanel1.add(loanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 286, 53));

        salarytxt.setBackground(new java.awt.Color(9, 9, 27));
        salarytxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salarytxt.setForeground(new java.awt.Color(255, 255, 255));
        salarytxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salarytxt.setText("Basic Salary");
        salarytxt.setOpaque(true);
        salarytxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                salarytxtMouseDragged(evt);
            }
        });
        salarytxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salarytxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salarytxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salarytxtMouseExited(evt);
            }
        });
        jPanel1.add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 286, 53));

        paybtn.setBackground(new java.awt.Color(9, 9, 27));
        paybtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paybtn.setForeground(new java.awt.Color(255, 255, 255));
        paybtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paybtn.setText("PaySlip");
        paybtn.setOpaque(true);
        paybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paybtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paybtnMouseExited(evt);
            }
        });
        jPanel1.add(paybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 286, 53));

        empbtn.setBackground(new java.awt.Color(9, 9, 27));
        empbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empbtn.setForeground(new java.awt.Color(255, 255, 255));
        empbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empbtn.setText("Employee Report");
        empbtn.setOpaque(true);
        empbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empbtnMouseExited(evt);
            }
        });
        jPanel1.add(empbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 286, 53));

        attendancebtn.setBackground(new java.awt.Color(9, 9, 27));
        attendancebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attendancebtn.setForeground(new java.awt.Color(255, 255, 255));
        attendancebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendancebtn.setText("Attendance");
        attendancebtn.setOpaque(true);
        attendancebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendancebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendancebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendancebtnMouseExited(evt);
            }
        });
        jPanel1.add(attendancebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 286, 53));

        leavesReportBtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesReportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesReportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesReportBtn.setText("Leaves Report");
        leavesReportBtn.setOpaque(true);
        leavesReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 290, 53));

        loanreportBtn.setBackground(new java.awt.Color(9, 9, 27));
        loanreportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanreportBtn.setForeground(new java.awt.Color(255, 255, 255));
        loanreportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanreportBtn.setText("Loans Report");
        loanreportBtn.setOpaque(true);
        loanreportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseExited(evt);
            }
        });
        jPanel1.add(loanreportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 53));

        paysheetbtn.setBackground(new java.awt.Color(9, 9, 27));
        paysheetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paysheetbtn.setForeground(new java.awt.Color(255, 255, 255));
        paysheetbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paysheetbtn.setText("Pay Sheet");
        paysheetbtn.setOpaque(true);
        paysheetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseExited(evt);
            }
        });
        jPanel1.add(paysheetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 286, 53));

        leavesbtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesbtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesbtn.setText("Leaves");
        leavesbtn.setOpaque(true);
        leavesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesbtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 286, 53));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manage Employee");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 29, 400, 53));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmpNamelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpNamelbl.setForeground(new java.awt.Color(0, 102, 102));
        EmpNamelbl.setText("Emp Name");
        jPanel2.add(EmpNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 26));

        EmpNametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpNametxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        EmpNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNametxtActionPerformed(evt);
            }
        });
        EmpNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmpNametxtKeyTyped(evt);
            }
        });
        jPanel2.add(EmpNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 280, 26));

        NIClbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NIClbl.setForeground(new java.awt.Color(0, 102, 102));
        NIClbl.setText("NIC");
        jPanel2.add(NIClbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 87, -1));

        NICtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NICtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        NICtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NICtxtKeyTyped(evt);
            }
        });
        jPanel2.add(NICtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 242, 25));

        Genderlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Genderlbl.setForeground(new java.awt.Color(0, 102, 102));
        Genderlbl.setText("Gender");
        jPanel2.add(Genderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 92, -1));

        buttonGroup1.add(Maleradiobtn);
        Maleradiobtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Maleradiobtn.setForeground(new java.awt.Color(102, 102, 102));
        Maleradiobtn.setText("Male");
        Maleradiobtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Maleradiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 70, -1));

        buttonGroup1.add(Femaleradiobtn);
        Femaleradiobtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Femaleradiobtn.setForeground(new java.awt.Color(102, 102, 102));
        Femaleradiobtn.setText("Female");
        Femaleradiobtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(Femaleradiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 91, -1));

        DateOfBirthlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DateOfBirthlbl.setForeground(new java.awt.Color(0, 102, 102));
        DateOfBirthlbl.setText("Date Of Birth");
        jPanel2.add(DateOfBirthlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 25));

        Addresslbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Addresslbl.setForeground(new java.awt.Color(0, 102, 102));
        Addresslbl.setText("Address");
        jPanel2.add(Addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 81, -1));

        Levellbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Levellbl.setForeground(new java.awt.Color(0, 102, 102));
        Levellbl.setText("Level");
        jPanel2.add(Levellbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 52, -1));

        TelNolbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TelNolbl.setForeground(new java.awt.Color(0, 102, 102));
        TelNolbl.setText("Tel No");
        jPanel2.add(TelNolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 501, 65, 26));

        DateOfJoininglbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DateOfJoininglbl.setForeground(new java.awt.Color(0, 102, 102));
        DateOfJoininglbl.setText("Date of Joining");
        jPanel2.add(DateOfJoininglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 570, -1, -1));

        Emailtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Emailtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        jPanel2.add(Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 642, 364, 26));

        dateOfBirthcalender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dateOfBirthcalender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateOfBirthcalender.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateOfBirthcalenderAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(dateOfBirthcalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 260, 230, 41));

        DateOfJoiningcalender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DateOfJoiningcalender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(DateOfJoiningcalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 570, 231, 42));

        Addresstxtarea.setColumns(20);
        Addresstxtarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Addresstxtarea.setRows(5);
        Addresstxtarea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(Addresstxtarea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 342, 329, 39));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(java.awt.Color.white);

        Savelbl.setBackground(new java.awt.Color(0, 102, 102));
        Savelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Savelbl.setForeground(java.awt.Color.white);
        Savelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Savelbl.setText("Save");
        Savelbl.setOpaque(true);
        Savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavelblMouseClicked(evt);
            }
        });

        Deletelbl.setBackground(new java.awt.Color(0, 102, 102));
        Deletelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Deletelbl.setForeground(java.awt.Color.white);
        Deletelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deletelbl.setText("Delete");
        Deletelbl.setOpaque(true);
        Deletelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletelblMouseClicked(evt);
            }
        });

        Updatelbl.setBackground(new java.awt.Color(0, 102, 102));
        Updatelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Updatelbl.setForeground(java.awt.Color.white);
        Updatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Updatelbl.setText("Update");
        Updatelbl.setOpaque(true);
        Updatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatelblMouseClicked(evt);
            }
        });

        Searchlbl.setBackground(new java.awt.Color(0, 102, 102));
        Searchlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Searchlbl.setForeground(java.awt.Color.white);
        Searchlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Searchlbl.setText("Search");
        Searchlbl.setOpaque(true);
        Searchlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Searchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(Updatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(Searchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(Deletelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 131, -1, -1));

        TelNotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TelNotxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        TelNotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelNotxtActionPerformed(evt);
            }
        });
        TelNotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelNotxtKeyTyped(evt);
            }
        });
        jPanel2.add(TelNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 501, 292, 26));

        Emaillbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Emaillbl.setForeground(new java.awt.Color(0, 102, 102));
        Emaillbl.setText("E mail");
        jPanel2.add(Emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 79, -1));

        Levelcombobox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Levelcombobox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Levelcombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Levelcombobox1ActionPerformed(evt);
            }
        });
        jPanel2.add(Levelcombobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 427, 242, 41));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/Add_32px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 427, 43, 45));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 126, 920, 700));

        EmpIdtxt.setEditable(false);
        EmpIdtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpIdtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        EmpIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIdtxtActionPerformed(evt);
            }
        });
        jPanel3.add(EmpIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 292, 26));

        EmpIdlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpIdlbl.setForeground(new java.awt.Color(255, 255, 255));
        EmpIdlbl.setText("EmpId");
        jPanel3.add(EmpIdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 111, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnMouseClicked

    private void SavelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavelblMouseClicked

        /* try {
            String selectedItem = (String) Levelcombobox1.getSelectedItem();
            String selectedItemCode = controller.getSelectedItemCode(selectedItem);
            System.out.println(selectedItemCode);
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        String EmpId = EmpIdtxt.getText();
        String EmpName = EmpNametxt.getText();
        String NIC = NICtxt.getText();
        buttonGroup1.add(Maleradiobtn);
        buttonGroup1.add(Femaleradiobtn);

        String gender = null;
        if (Maleradiobtn.isSelected()) {
            gender = "Male";
        } else if (Femaleradiobtn.isSelected()) {
            gender = "Female";
        }

        String DOB = ((JTextField) dateOfBirthcalender.getDateEditor().getUiComponent()).getText();
        dateOfBirthcalender.setDateFormatString("yyyy-MM-dd");
        String Address = Addresstxtarea.getText();

        /* String level="";
        try {
            level = controller.getSelectedItemCode(Levelcombobox1.getSelectedItem().toString());
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        String level = (String) Levelcombobox1.getSelectedItem();
        String Tel = TelNotxt.getText();
        String DOJ = ((JTextField) DateOfJoiningcalender.getDateEditor().getUiComponent()).getText();
        String Email = Emailtxt.getText();

        EmployeeDTO employee = new EmployeeDTO(EmpId, EmpName, Address, gender, DOB,Tel, DOJ,NIC, Email,level);

        if (!update) {
            try {
                boolean result = controller.saveEmployee(employee);
                if (result) {
                    JOptionPane.showMessageDialog(this, "Customer has been added successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the customer");
                }
            } catch (Exception ex) {
                Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        clearTextFields();   
         generateEmpId();

    }//GEN-LAST:event_SavelblMouseClicked

    private void DeletelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletelblMouseClicked

        try {
            boolean result = controller.deleteEmployee(EmpIdtxt.getText());
            if (result) {
                JOptionPane.showMessageDialog(this, "Customer has been deleted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the customer");
            }
            clearTextFields();
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearTextFields();
    }//GEN-LAST:event_DeletelblMouseClicked

    private void UpdatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatelblMouseClicked
        try {
            String EmpId = EmpIdtxt.getText();
            String EmpName = EmpNametxt.getText();
            String NIC = NICtxt.getText();
            buttonGroup1.add(Maleradiobtn);
            buttonGroup1.add(Femaleradiobtn);

            String gender = null;
            if (Maleradiobtn.isSelected()) {
                gender = "Male";
            } else if (Femaleradiobtn.isSelected()) {
                gender = "Female";
            }
            String DOB = ((JTextField) dateOfBirthcalender.getDateEditor().getUiComponent()).getText();
            String Address = Addresstxtarea.getText();

            /*String level="";
        try {
            level = controller.getSelectedItemCode(Levelcombobox1.getSelectedItem().toString());
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }*/
            String level = (String) Levelcombobox1.getSelectedItem();
            String Tel = TelNotxt.getText();
            String DOJ = ((JTextField) DateOfJoiningcalender.getDateEditor().getUiComponent()).getText();
            String Email = Emailtxt.getText();

            EmployeeDTO employee = new EmployeeDTO(EmpId, EmpName, Address, gender, DOB,Tel, DOJ,NIC, Email,level);
            boolean result = controller.updateEmployee(employee);

            if (result) {
                JOptionPane.showMessageDialog(this, "Customer has been updated successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the customer");
            }
        } catch (Exception ex) {
            Logger.getLogger(level.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearTextFields();
    }//GEN-LAST:event_UpdatelblMouseClicked

    private void SearchlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchlblMouseClicked
        String eName = EmpNametxt.getText();
             try {
            EmployeeDTO searchEmployee;
                 
            searchEmployee = controller.searchEmployee(eName);
            
            EmpIdtxt.setText(searchEmployee.geteId());
            NICtxt.setText(searchEmployee.getNic());
            // System.out.println(searchEmployee.getLeId());
//            if (Maleradiobtn.equals("male")) {
//                buttonGroup1.setSelected((ButtonModel) buttonGroup1, update);
//            } else {
//                buttonGroup1.setSelected((ButtonModel) Femaleradiobtn, true);
//            }
            Date d=java.sql.Date.valueOf(searchEmployee.getDob());
            
                 System.out.println(searchEmployee.getDob());
            Addresstxtarea.setText(searchEmployee.getAddress());
            System.out.println(searchEmployee.getAddress());
            Levelcombobox1.setSelectedItem(searchEmployee.getLeId());
            TelNotxt.setText(searchEmployee.getTelNo());
            Date date=java.sql.Date.valueOf(searchEmployee.getDateOfJoining());
            Emailtxt.setText(searchEmployee.geteMail());
                 System.out.println(searchEmployee.getLeId());
            DateOfJoiningcalender.setDate(date);
            dateOfBirthcalender.setDate(d);
        } catch (Exception ex) {
            Logger.getLogger(level.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchlblMouseClicked

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
        homebtn.setFont(new Font("Lucida Bright", 1, 30));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
        homebtn.setFont(new Font("Tahoma", 1, 18));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseExited

    private void NICtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICtxtKeyTyped
        validation.NIC(NICtxt);
    }//GEN-LAST:event_NICtxtKeyTyped

    private void TelNotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelNotxtKeyTyped

    }//GEN-LAST:event_TelNotxtKeyTyped

    private void EmpIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIdtxtActionPerformed
        EmpNametxt.requestFocus();
    }//GEN-LAST:event_EmpIdtxtActionPerformed

    private void dateOfBirthcalenderAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateOfBirthcalenderAncestorAdded
        Addresstxtarea.requestFocus();
    }//GEN-LAST:event_dateOfBirthcalenderAncestorAdded

    private void Levelcombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Levelcombobox1ActionPerformed
        TelNotxt.requestFocus();
    }//GEN-LAST:event_Levelcombobox1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
          level l = new level();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void TelNotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelNotxtActionPerformed
        validation.phoneNumber(TelNotxt);
    }//GEN-LAST:event_TelNotxtActionPerformed

    private void loanbtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loanbtnMouseDragged

    private void loanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseClicked
        loan l = new loan();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanbtnMouseClicked

    private void loanbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseEntered
        loanbtn.setFont(new Font("Lucida Bright", 1, 30));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseEntered

    private void loanbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseExited
        loanbtn.setFont(new Font("Tahoma", 1, 18));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseExited

    private void salarytxtMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_salarytxtMouseDragged

    private void salarytxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseClicked
       basicSalary b = new basicSalary();
       b.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_salarytxtMouseClicked

    private void salarytxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseEntered
        salarytxt.setFont(new Font("Lucida Bright", 1, 30));
        salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseEntered

    private void salarytxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseExited
         salarytxt.setFont(new Font("Tahoma", 1, 18));
         salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseExited

    private void paybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseClicked
        paySlip l = new paySlip();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paybtnMouseClicked

    private void paybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseEntered
        paybtn.setFont(new Font("Lucida Bright", 1, 30));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseEntered

    private void paybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseExited
        paybtn.setFont(new Font("Tahoma", 1, 18));
        paybtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paybtnMouseExited

    private void empbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseClicked
        employeeReport e=new employeeReport();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empbtnMouseClicked

    private void empbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseEntered
        empbtn.setFont(new Font("Lucida Bright", 1, 30));
        empbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_empbtnMouseEntered

    private void empbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseExited
        empbtn.setFont(new Font("Thahoma",1,18));
        empbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_empbtnMouseExited

    private void attendancebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseClicked
        attendance p=new attendance();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendancebtnMouseClicked

    private void attendancebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseEntered
        attendancebtn.setFont(new Font("Lucida Bright", 1, 30));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseEntered

    private void attendancebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseExited
        attendancebtn.setFont(new Font("Tahoma", 1, 18));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseExited

    private void leavesReportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseClicked
        leavesReport l=new leavesReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesReportBtnMouseClicked

    private void leavesReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseEntered
        leavesReportBtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseEntered

    private void leavesReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseExited
        leavesReportBtn.setFont(new Font("Tahoma", 1, 18));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseExited

    private void loanreportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseClicked
        loanReport l = new loanReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanreportBtnMouseClicked

    private void loanreportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseEntered
       loanreportBtn.setFont(new Font("Lucida Bright", 1, 30));
       loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseEntered

    private void loanreportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseExited
        loanreportBtn.setFont(new Font("Tahoma", 1, 18));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseExited

    private void paysheetbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseClicked
       paySheet p = new paySheet();
       p.setVisible(true);
       this.dispose();
               
    }//GEN-LAST:event_paysheetbtnMouseClicked

    private void paysheetbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseEntered
       paysheetbtn.setFont(new Font("Lucida Bright", 1, 30));
       paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseEntered

    private void paysheetbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseExited
        paysheetbtn.setFont(new Font("Tahoma", 1, 18));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseExited

    private void leavesbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseClicked
        leaves l = new leaves();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesbtnMouseClicked

    private void leavesbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseEntered
       leavesbtn.setFont(new Font("Lucida Bright", 1, 30));
       leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseEntered

    private void leavesbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseExited
        leavesbtn.setFont(new Font("Tahoma", 1, 18));
        leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseExited

    private void EmpNametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpNametxtKeyTyped
        validation.name(EmpNametxt);
    }//GEN-LAST:event_EmpNametxtKeyTyped

    private void EmpNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNametxtActionPerformed
        NICtxt.requestFocus();
    }//GEN-LAST:event_EmpNametxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addresslbl;
    private javax.swing.JTextArea Addresstxtarea;
    private javax.swing.JLabel DateOfBirthlbl;
    private com.toedter.calendar.JDateChooser DateOfJoiningcalender;
    private javax.swing.JLabel DateOfJoininglbl;
    private javax.swing.JLabel Deletelbl;
    private javax.swing.JLabel Emaillbl;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JLabel EmpIdlbl;
    private javax.swing.JTextField EmpIdtxt;
    private javax.swing.JLabel EmpNamelbl;
    private javax.swing.JTextField EmpNametxt;
    private javax.swing.JLabel Employeetxt;
    private javax.swing.JRadioButton Femaleradiobtn;
    private javax.swing.JLabel Genderlbl;
    private javax.swing.JComboBox<String> Levelcombobox1;
    private javax.swing.JLabel Levellbl;
    private javax.swing.JRadioButton Maleradiobtn;
    private javax.swing.JLabel NIClbl;
    private javax.swing.JTextField NICtxt;
    private javax.swing.JLabel Savelbl;
    private javax.swing.JLabel Searchlbl;
    private javax.swing.JLabel TelNolbl;
    private javax.swing.JTextField TelNotxt;
    private javax.swing.JLabel Updatelbl;
    private javax.swing.JLabel attendancebtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateOfBirthcalender;
    private javax.swing.JLabel empbtn;
    private javax.swing.JLabel homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leavesReportBtn;
    private javax.swing.JLabel leavesbtn;
    private javax.swing.JLabel loanbtn;
    private javax.swing.JLabel loanreportBtn;
    private javax.swing.JLabel paybtn;
    private javax.swing.JLabel paysheetbtn;
    private javax.swing.JLabel salarytxt;
    // End of variables declaration//GEN-END:variables

    private void getAllLevels() {
        try {
            ArrayList<String> allLeves = controller.getAllLeves();
            for (String level : allLeves) {
                Levelcombobox1.addItem(level);
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearTextFields() {
        //EmpIdtxt.setText("");
        EmpNametxt.setText("");
        NICtxt.setText("");
         dateOfBirthcalender.setDateFormatString("");
        Maleradiobtn.setText("");
        Femaleradiobtn.setText("");
        Addresstxtarea.setText("");
        TelNotxt.setText("");
         DateOfJoiningcalender.setDateFormatString("");
        Emailtxt.setText("");

    }

    private void generateEmpId() {

        try {
            EmpIdtxt.setText(IDGenerator.getNewID("Employee", "eId", "E"));
        } catch (SQLException ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
