/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.payrollSystem.view;

import com.jidesoft.swing.ComboBoxSearchable;
import ik.ijse.payrollSystem.idgenerator.IDGenerator;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.payrollSystem.business.custom.LoansBo;
import lk.ijse.payrollSystem.controller.paySlipController;
import lk.ijse.payrollSystem.db.DBConnection;
import lk.ijse.payrollSystem.dto.EmployeeDTO;
import lk.ijse.payrollSystem.dto.LeavesDTO;
import lk.ijse.payrollSystem.dto.LevelDTO;
import lk.ijse.payrollSystem.dto.LoansDTO;
import lk.ijse.payrollSystem.dto.SalaryDTO;
import lk.ijse.payrollSystem.dto.SalaryDetailsDTO;
import lk.ijse.payrollSystem.entity.SalaryDetails;
import lk.ijse.payrollSystem.validation.validation;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class paySlip extends javax.swing.JFrame {
      private paySlipController controller;
    private boolean update=false;
    

    /**
     * Creates new form paySlip
     */
    public paySlip() {
        controller=new paySlipController();
        initComponents();
        setDate();
        getAllEmployees();
         //getAllLevels();
        generateslipNo();
        generatesalId();
        //ComboBoxSearchable searchable1=new ComboBoxSearchable(combo1);
        paySlipNotxt.setVisible(false);
        salIdtxt.setVisible(false);
        ComboBoxSearchable searchable1=new ComboBoxSearchable(EmpIdcombobox);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homebtn = new javax.swing.JLabel();
        loanbtn = new javax.swing.JLabel();
        salarytxt = new javax.swing.JLabel();
        empbtn = new javax.swing.JLabel();
        attendancebtn = new javax.swing.JLabel();
        leavesReportBtn = new javax.swing.JLabel();
        paysheetbtn = new javax.swing.JLabel();
        leavesbtn = new javax.swing.JLabel();
        Employeetxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loanreportBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Levellbl = new javax.swing.JLabel();
        EmpNamelbl = new javax.swing.JLabel();
        Levelcombobox = new javax.swing.JComboBox<>();
        BasicSalaryAmountlbl = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        BasicSalaryAmounttxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Taxeslbl = new javax.swing.JLabel();
        Loanlbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nopaytxt = new javax.swing.JTextField();
        Damagestxt = new javax.swing.JTextField();
        Loantxt = new javax.swing.JTextField();
        Damageslbl = new javax.swing.JLabel();
        EPFtxt = new javax.swing.JTextField();
        EPFlbl = new javax.swing.JLabel();
        GrossDeductionlbl = new javax.swing.JLabel();
        GrossDeductiontxt = new javax.swing.JTextField();
        NetSalarylbl = new javax.swing.JLabel();
        NetSalarytxt = new javax.swing.JTextField();
        Calculatelbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        searchlbl = new javax.swing.JLabel();
        Printlbl = new javax.swing.JLabel();
        savelbl = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        Datelbl1 = new javax.swing.JLabel();
        paySlipNotxt = new javax.swing.JTextField();
        Datelbl2 = new javax.swing.JLabel();
        salIdtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmpIdcombobox = new com.jidesoft.swing.AutoCompletionComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 9, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homebtn.setBackground(new java.awt.Color(9, 9, 27));
        homebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebtn.setForeground(new java.awt.Color(255, 255, 255));
        homebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/home2.png"))); // NOI18N
        homebtn.setText("Home");
        homebtn.setOpaque(true);
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 286, 53));

        loanbtn.setBackground(new java.awt.Color(9, 9, 27));
        loanbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanbtn.setForeground(new java.awt.Color(255, 255, 255));
        loanbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanbtn.setText("Loan");
        loanbtn.setOpaque(true);
        loanbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                loanbtnMouseDragged(evt);
            }
        });
        loanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanbtnMouseExited(evt);
            }
        });
        jPanel1.add(loanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 286, 53));

        salarytxt.setBackground(new java.awt.Color(9, 9, 27));
        salarytxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salarytxt.setForeground(new java.awt.Color(255, 255, 255));
        salarytxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salarytxt.setText("Basic Salary");
        salarytxt.setOpaque(true);
        salarytxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                salarytxtMouseDragged(evt);
            }
        });
        salarytxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salarytxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salarytxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salarytxtMouseExited(evt);
            }
        });
        jPanel1.add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 286, 53));

        empbtn.setBackground(new java.awt.Color(9, 9, 27));
        empbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        empbtn.setForeground(new java.awt.Color(255, 255, 255));
        empbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empbtn.setText("Employee Report");
        empbtn.setOpaque(true);
        empbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empbtnMouseExited(evt);
            }
        });
        jPanel1.add(empbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 286, 53));

        attendancebtn.setBackground(new java.awt.Color(9, 9, 27));
        attendancebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attendancebtn.setForeground(new java.awt.Color(255, 255, 255));
        attendancebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendancebtn.setText("Attendance");
        attendancebtn.setOpaque(true);
        attendancebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendancebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendancebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendancebtnMouseExited(evt);
            }
        });
        jPanel1.add(attendancebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 286, 60));

        leavesReportBtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesReportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesReportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesReportBtn.setText("Leaves Report");
        leavesReportBtn.setOpaque(true);
        leavesReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesReportBtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 280, 53));

        paysheetbtn.setBackground(new java.awt.Color(9, 9, 27));
        paysheetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paysheetbtn.setForeground(new java.awt.Color(255, 255, 255));
        paysheetbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paysheetbtn.setText("Pay Sheet");
        paysheetbtn.setOpaque(true);
        paysheetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paysheetbtnMouseExited(evt);
            }
        });
        jPanel1.add(paysheetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 286, 53));

        leavesbtn.setBackground(new java.awt.Color(9, 9, 27));
        leavesbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leavesbtn.setForeground(new java.awt.Color(255, 255, 255));
        leavesbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesbtn.setText("Leaves");
        leavesbtn.setOpaque(true);
        leavesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leavesbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leavesbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leavesbtnMouseExited(evt);
            }
        });
        jPanel1.add(leavesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 286, 53));

        Employeetxt.setBackground(new java.awt.Color(9, 9, 27));
        Employeetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Employeetxt.setForeground(new java.awt.Color(255, 255, 255));
        Employeetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employeetxt.setText("Manage Employee");
        Employeetxt.setOpaque(true);
        Employeetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeetxtMouseExited(evt);
            }
        });
        jPanel1.add(Employeetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 286, 53));

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PaySlip");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 50));

        loanreportBtn.setBackground(new java.awt.Color(9, 9, 27));
        loanreportBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanreportBtn.setForeground(new java.awt.Color(255, 255, 255));
        loanreportBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loanreportBtn.setText("Loans Report");
        loanreportBtn.setOpaque(true);
        loanreportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanreportBtnMouseExited(evt);
            }
        });
        jPanel1.add(loanreportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 280, 53));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Levellbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Levellbl.setForeground(new java.awt.Color(0, 102, 102));
        Levellbl.setText("Level");
        jPanel3.add(Levellbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 52, -1));

        EmpNamelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpNamelbl.setForeground(new java.awt.Color(0, 102, 102));
        EmpNamelbl.setText("Emp Name");
        jPanel3.add(EmpNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 26));

        Levelcombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Levelcombobox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Levelcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LevelcomboboxItemStateChanged(evt);
            }
        });
        Levelcombobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LevelcomboboxMouseClicked(evt);
            }
        });
        jPanel3.add(Levelcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 228, 42));

        BasicSalaryAmountlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BasicSalaryAmountlbl.setForeground(new java.awt.Color(0, 102, 102));
        BasicSalaryAmountlbl.setText("Basic Salary Amount");
        jPanel3.add(BasicSalaryAmountlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 42));

        Datelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Datelbl.setForeground(new java.awt.Color(0, 102, 102));
        Datelbl.setText("Date ");
        jPanel3.add(Datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 61, -1));

        BasicSalaryAmounttxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BasicSalaryAmounttxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        BasicSalaryAmounttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BasicSalaryAmounttxtKeyTyped(evt);
            }
        });
        jPanel3.add(BasicSalaryAmounttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 229, 26));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        Taxeslbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Taxeslbl.setForeground(new java.awt.Color(0, 51, 51));
        Taxeslbl.setText("No Pay");

        Loanlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Loanlbl.setForeground(new java.awt.Color(0, 51, 51));
        Loanlbl.setText("Loan");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText(" Type");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Amount");

        nopaytxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nopaytxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        nopaytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopaytxtActionPerformed(evt);
            }
        });
        nopaytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nopaytxtKeyTyped(evt);
            }
        });

        Damagestxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Damagestxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Damagestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamagestxtActionPerformed(evt);
            }
        });
        Damagestxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DamagestxtKeyTyped(evt);
            }
        });

        Loantxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Loantxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        Loantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoantxtActionPerformed(evt);
            }
        });
        Loantxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LoantxtKeyTyped(evt);
            }
        });

        Damageslbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Damageslbl.setForeground(new java.awt.Color(0, 51, 51));
        Damageslbl.setText("Damages");

        EPFtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EPFtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        EPFtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EPFtxtKeyTyped(evt);
            }
        });

        EPFlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EPFlbl.setForeground(new java.awt.Color(0, 51, 51));
        EPFlbl.setText("EPF");

        GrossDeductionlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GrossDeductionlbl.setText("Gross Deduction");

        GrossDeductiontxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GrossDeductiontxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        GrossDeductiontxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GrossDeductiontxtKeyTyped(evt);
            }
        });

        NetSalarylbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NetSalarylbl.setText("Net Salary");

        NetSalarytxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NetSalarytxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        NetSalarytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NetSalarytxtKeyTyped(evt);
            }
        });

        Calculatelbl.setBackground(new java.awt.Color(255, 255, 255));
        Calculatelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Calculatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calculatelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/payrollSystem/asset/calcualter.png"))); // NOI18N
        Calculatelbl.setText("Calculate  ");
        Calculatelbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        Calculatelbl.setOpaque(true);
        Calculatelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatelblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(GrossDeductionlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GrossDeductiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(EPFlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EPFtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Damageslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Damagestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Loanlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Loantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Taxeslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(nopaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(NetSalarylbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NetSalarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(Calculatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nopaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Taxeslbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Loanlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Loantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Damageslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Damagestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EPFtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPFlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrossDeductionlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrossDeductiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetSalarylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NetSalarytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        searchlbl.setBackground(new java.awt.Color(0, 102, 102));
        searchlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchlbl.setForeground(java.awt.Color.white);
        searchlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchlbl.setText("Search");
        searchlbl.setOpaque(true);
        searchlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlblMouseClicked(evt);
            }
        });

        Printlbl.setBackground(new java.awt.Color(0, 102, 102));
        Printlbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Printlbl.setForeground(java.awt.Color.white);
        Printlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Printlbl.setText("Print");
        Printlbl.setOpaque(true);
        Printlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintlblMouseClicked(evt);
            }
        });

        savelbl.setBackground(new java.awt.Color(0, 102, 102));
        savelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savelbl.setForeground(java.awt.Color.white);
        savelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savelbl.setText("Save");
        savelbl.setOpaque(true);
        savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savelblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Printlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(searchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Printlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, -1, 330));

        datetxt.setEditable(false);
        datetxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datetxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        jPanel3.add(datetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 229, 26));

        Datelbl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Datelbl1.setForeground(new java.awt.Color(255, 255, 255));
        Datelbl1.setText("Sal Id");
        jPanel3.add(Datelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 100, 27));

        paySlipNotxt.setEditable(false);
        paySlipNotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paySlipNotxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        jPanel3.add(paySlipNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 229, 26));

        Datelbl2.setBackground(new java.awt.Color(255, 255, 255));
        Datelbl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Datelbl2.setForeground(new java.awt.Color(255, 255, 255));
        Datelbl2.setText("Pay Slip No");
        jPanel3.add(Datelbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 27));

        salIdtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salIdtxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        jPanel3.add(salIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 229, 26));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PaySlip");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 361, 53));

        EmpIdcombobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpIdcombobox.setStrict(false);
        EmpIdcombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EmpIdcomboboxItemStateChanged(evt);
            }
        });
        EmpIdcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIdcomboboxActionPerformed(evt);
            }
        });
        jPanel3.add(EmpIdcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintlblMouseClicked
        try {
            InputStream is = getClass().getResourceAsStream("/lk/ijse/payrollSystem/reports/paySlip.jasper");
            HashMap m = new HashMap();
            JasperPrint fillReport = JasperFillManager.fillReport(is, m, DBConnection.getInstance().getConnection());
            JasperViewer.viewReport(fillReport);
        } catch (Exception ex) {
            Logger.getLogger(employeeReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_PrintlblMouseClicked

    private void searchlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlblMouseClicked
        String empName =EmpIdcombobox.getSelectedItem().toString();
        try {
            SalaryDetailsDTO searchSalaryDetails;
            searchSalaryDetails = controller.searchSalaryDetails(empName);
           // EmpIdcombobox.setSelectedItem(searchSalaryDetails.getEmpId());
            paySlipNotxt.setText(searchSalaryDetails.getSdId());
            Levelcombobox.setSelectedItem(searchSalaryDetails.getLevel());
            BasicSalaryAmounttxt.setText(searchSalaryDetails.getBasicSalaryAmount().toString());
            salIdtxt.setText(searchSalaryDetails.getSalId());
            datetxt.setText(searchSalaryDetails.getDate());
            nopaytxt.setText(searchSalaryDetails.getNoPay().toString());
            Loantxt.setText(searchSalaryDetails.getLoan().toString());
            Damagestxt.setText(searchSalaryDetails.getDamages().toString());
            EPFtxt.setText(searchSalaryDetails.getEpf().toString());
            GrossDeductiontxt.setText(searchSalaryDetails.getGrossDeduction().toString());
            NetSalarytxt.setText(searchSalaryDetails.getNetSalary().toString());
        } catch (Exception ex) {
            Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchlblMouseClicked

    private void savelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savelblMouseClicked
        String sdId=paySlipNotxt.getText();
        String EmpId=(String)EmpIdcombobox.getSelectedItem();
        String Empname=EmpIdcombobox.getSelectedItem().toString();
        String level=(String)Levelcombobox.getSelectedItem();
        BigDecimal basicSalaryAmount=new BigDecimal(BasicSalaryAmounttxt.getText());
        String salId=salIdtxt.getText();

        String date=datetxt.getText();
        BigDecimal NoPay= new BigDecimal(nopaytxt.getText());
        BigDecimal loan=new BigDecimal(Loantxt.getText());
        BigDecimal damages=new BigDecimal(Damagestxt.getText());
        BigDecimal EPF=new BigDecimal(EPFtxt.getText());
        BigDecimal grossDeduction=new BigDecimal(GrossDeductiontxt.getText());
        BigDecimal netSalary=new BigDecimal(NetSalarytxt.getText());

        SalaryDetailsDTO salaryDetails=new SalaryDetailsDTO(sdId,EmpId,Empname,level,basicSalaryAmount,salId,date,NoPay,loan,damages,EPF,grossDeduction,netSalary);

        if (!update) {
            try {
                boolean result = controller.saveSalaryDetails(salaryDetails);
                if (result) {
                    JOptionPane.showMessageDialog(this, "salaryDetails has been added successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the salaryDetails");
                }
            } catch (Exception ex) {
                Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        clearTextFields();

        generateslipNo();
        generatesalId();
    }//GEN-LAST:event_savelblMouseClicked

    private void CalculatelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatelblMouseClicked
        double basicSalaryAmount=Double.parseDouble(BasicSalaryAmounttxt.getText());
        double noPay=Double.parseDouble(nopaytxt.getText());
        double loan=Double.parseDouble(Loantxt.getText());
        double damages=Double.parseDouble(Damagestxt.getText());
        double EPF=Double.parseDouble(EPFtxt.getText());

        double GrossDeduction= noPay + loan + damages + EPF ;
        String x=String.valueOf( String.format("%.2f", GrossDeduction));

        GrossDeductiontxt.setText(x);

        double netSalary = basicSalaryAmount - GrossDeduction;
        String y=String.valueOf( String.format("%.2f",netSalary ));
        NetSalarytxt.setText(y);

    }//GEN-LAST:event_CalculatelblMouseClicked

    private void NetSalarytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NetSalarytxtKeyTyped
        validation.priceText(NetSalarytxt);
    }//GEN-LAST:event_NetSalarytxtKeyTyped

    private void GrossDeductiontxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrossDeductiontxtKeyTyped
        validation.priceText(GrossDeductiontxt);
    }//GEN-LAST:event_GrossDeductiontxtKeyTyped

    private void EPFtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EPFtxtKeyTyped
        validation.priceText(EPFtxt);
    }//GEN-LAST:event_EPFtxtKeyTyped

    private void LoantxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoantxtKeyTyped
        validation.priceText(Loantxt);
    }//GEN-LAST:event_LoantxtKeyTyped

    private void LoantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoantxtActionPerformed
        Damagestxt.requestFocus();
    }//GEN-LAST:event_LoantxtActionPerformed

    private void DamagestxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DamagestxtKeyTyped
        validation.priceText(Damagestxt);
    }//GEN-LAST:event_DamagestxtKeyTyped

    private void DamagestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamagestxtActionPerformed
        EPFtxt.requestFocus();
    }//GEN-LAST:event_DamagestxtActionPerformed

    private void nopaytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nopaytxtKeyTyped
        validation.priceText(nopaytxt);
    }//GEN-LAST:event_nopaytxtKeyTyped

    private void nopaytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopaytxtActionPerformed
        Loantxt.requestFocus();
    }//GEN-LAST:event_nopaytxtActionPerformed

    private void BasicSalaryAmounttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BasicSalaryAmounttxtKeyTyped
        validation.priceText(BasicSalaryAmounttxt);
    }//GEN-LAST:event_BasicSalaryAmounttxtKeyTyped

    private void LevelcomboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LevelcomboboxMouseClicked

    }//GEN-LAST:event_LevelcomboboxMouseClicked

    private void LevelcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LevelcomboboxItemStateChanged
        try {
            String leId=(String) Levelcombobox.getSelectedItem();
            LevelDTO level=controller.searchlevels(leId);
            if(level!=null){
                BasicSalaryAmounttxt.setText(level.getBasicSalary().toString());
                EPFtxt.setText(level.getEPFAmount().toString());
            }
        } catch (Exception ex) {
            Logger.getLogger(leaves.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_LevelcomboboxItemStateChanged

    private void EmpIdcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIdcomboboxActionPerformed
        // TODO add your handling code here:
        try {

            String eId=(String) EmpIdcombobox.getSelectedItem();
            EmployeeDTO employee=controller.searchEmployees(eId);

            LoansDTO l=controller.getLoan(eId);

            //SalaryDetailsDTO sd=controller.getSalaryDetail(eId);
            if (employee != null) {

                if (l != null) {

                    Loantxt.setText(l.getTotal() + "");
                }else{
                    Loantxt.setText("0.00");
                }
                int i = 0;

                LeavesDTO ld = controller.searchLeaves(employee.getName());

                if (ld != null) {

                    i = Integer.parseInt(ld.getBalanceLeave());

                    if (i >= 0) {
                        nopaytxt.setText("0.00");
                    } else {
                        double v = (i * -1) * 500;
                        System.out.println(v);
                        nopaytxt.setText(v + "");

                    }
                } else {
                    nopaytxt.setText("0.00");
                }
                ////                    else{
                    //                   Loantxt.setText("0.00");
                    //               }
                //               BigDecimal bd=sd.getNoPay();
                //               double d=bd.doubleValue();
                //               if(d>=0){
                    //                    nopaytxt.setText("0.0");
                    //               }else{
                    //                   double v=(d*-1)*500;
                    //                   nopaytxt.setText(v+"");
                    //               }
            }
        } catch (Exception ex) {
            Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmpIdcomboboxActionPerformed

    private void EmpIdcomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EmpIdcomboboxItemStateChanged
        try {
            String eId = (String) EmpIdcombobox.getSelectedItem();

            EmployeeDTO employee = controller.searchEmployees(eId);

            if (employee != null) {
                Levelcombobox.removeAllItems();
                //EmpNametxt.setText(employee.getName());
                Levelcombobox.addItem(employee.getLeId());

            }
        } catch (Exception ex) {
            Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmpIdcomboboxItemStateChanged

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnMouseClicked

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
        homebtn.setFont(new Font("Lucida Bright", 1, 30));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
        homebtn.setFont(new Font("Tahoma", 1, 18));
        homebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_homebtnMouseExited

    private void loanbtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_loanbtnMouseDragged

    private void loanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseClicked
        loan l = new loan();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanbtnMouseClicked

    private void loanbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseEntered
        loanbtn.setFont(new Font("Lucida Bright", 1, 30));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseEntered

    private void loanbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanbtnMouseExited
        loanbtn.setFont(new Font("Tahoma", 1, 18));
        loanbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanbtnMouseExited

    private void salarytxtMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_salarytxtMouseDragged

    private void salarytxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseClicked
        basicSalary b = new basicSalary();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salarytxtMouseClicked

    private void salarytxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseEntered
        salarytxt.setFont(new Font("Lucida Bright", 1, 30));
        salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseEntered

    private void salarytxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salarytxtMouseExited
        salarytxt.setFont(new Font("Tahoma", 1, 18));
        salarytxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_salarytxtMouseExited

    private void empbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseClicked
        employeeReport e=new employeeReport();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empbtnMouseClicked

    private void empbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseEntered
        empbtn.setFont(new Font("Lucida Bright", 1, 30));
        empbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_empbtnMouseEntered

    private void empbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empbtnMouseExited
        empbtn.setFont(new Font("Thahoma",1,18));
        empbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_empbtnMouseExited

    private void attendancebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseClicked
        attendance p=new attendance();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendancebtnMouseClicked

    private void attendancebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseEntered
        attendancebtn.setFont(new Font("Lucida Bright", 1, 30));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseEntered

    private void attendancebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendancebtnMouseExited
        attendancebtn.setFont(new Font("Tahoma", 1, 18));
        attendancebtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_attendancebtnMouseExited

    private void leavesReportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseClicked
        leavesReport l=new leavesReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesReportBtnMouseClicked

    private void leavesReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseEntered
        leavesReportBtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseEntered

    private void leavesReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesReportBtnMouseExited
        leavesReportBtn.setFont(new Font("Tahoma", 1, 18));
        leavesReportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesReportBtnMouseExited

    private void paysheetbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseClicked
        paySheet p = new paySheet();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paysheetbtnMouseClicked

    private void paysheetbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseEntered
        paysheetbtn.setFont(new Font("Lucida Bright", 1, 30));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseEntered

    private void paysheetbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysheetbtnMouseExited
        paysheetbtn.setFont(new Font("Tahoma", 1, 18));
        paysheetbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_paysheetbtnMouseExited

    private void leavesbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseClicked
        leaves l = new leaves();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leavesbtnMouseClicked

    private void leavesbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseEntered
        leavesbtn.setFont(new Font("Lucida Bright", 1, 30));
        leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseEntered

    private void leavesbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leavesbtnMouseExited
        leavesbtn.setFont(new Font("Tahoma", 1, 18));
        leavesbtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_leavesbtnMouseExited

    private void EmployeetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseClicked
        ManageEmployee m = new ManageEmployee();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmployeetxtMouseClicked

    private void EmployeetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseEntered
        Employeetxt.setFont(new Font("Lucida Bright", 1, 30));
        Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseEntered

    private void EmployeetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeetxtMouseExited
        Employeetxt.setFont(new Font("Tahoma", 1, 18));
        Employeetxt.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_EmployeetxtMouseExited

    private void loanreportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseClicked
        loanReport l = new loanReport();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanreportBtnMouseClicked

    private void loanreportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseEntered
        loanreportBtn.setFont(new Font("Lucida Bright", 1, 30));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseEntered

    private void loanreportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanreportBtnMouseExited
        loanreportBtn.setFont(new Font("Tahoma", 1, 18));
        loanreportBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loanreportBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paySlip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BasicSalaryAmountlbl;
    private javax.swing.JTextField BasicSalaryAmounttxt;
    private javax.swing.JLabel Calculatelbl;
    private javax.swing.JLabel Damageslbl;
    private javax.swing.JTextField Damagestxt;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JLabel Datelbl1;
    private javax.swing.JLabel Datelbl2;
    private javax.swing.JLabel EPFlbl;
    private javax.swing.JTextField EPFtxt;
    private com.jidesoft.swing.AutoCompletionComboBox EmpIdcombobox;
    private javax.swing.JLabel EmpNamelbl;
    private javax.swing.JLabel Employeetxt;
    private javax.swing.JLabel GrossDeductionlbl;
    private javax.swing.JTextField GrossDeductiontxt;
    private javax.swing.JComboBox<String> Levelcombobox;
    private javax.swing.JLabel Levellbl;
    private javax.swing.JLabel Loanlbl;
    private javax.swing.JTextField Loantxt;
    private javax.swing.JLabel NetSalarylbl;
    private javax.swing.JTextField NetSalarytxt;
    private javax.swing.JLabel Printlbl;
    private javax.swing.JLabel Taxeslbl;
    private javax.swing.JLabel attendancebtn;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel empbtn;
    private javax.swing.JLabel homebtn;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel leavesReportBtn;
    private javax.swing.JLabel leavesbtn;
    private javax.swing.JLabel loanbtn;
    private javax.swing.JLabel loanreportBtn;
    private javax.swing.JTextField nopaytxt;
    private javax.swing.JTextField paySlipNotxt;
    private javax.swing.JLabel paysheetbtn;
    private javax.swing.JTextField salIdtxt;
    private javax.swing.JLabel salarytxt;
    private javax.swing.JLabel savelbl;
    private javax.swing.JLabel searchlbl;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        datetxt.setText(sdf.format(date));
    }

    private void getAllLevels() {
          try {
            ArrayList<String> allLeves = controller.getAllLeves();
            for (String level : allLeves) {
                Levelcombobox.addItem(level);
            }
        } catch (Exception ex) {
            Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getAllEmployees() {
         try {
            ArrayList<String> allEmployees = controller.getEmployees();
            for (String employee : allEmployees) {
                EmpIdcombobox.addItem(employee);
            }
        } catch (Exception ex) {
            Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearTextFields() {
        //EmpNametxt.setText("");
        BasicSalaryAmounttxt.setText("");
        salIdtxt.setText("");
       paySlipNotxt.setText("");
        nopaytxt.setText("");
        Loantxt.setText("");
        Damagestxt.setText("");
        EPFtxt.setText("");
        GrossDeductiontxt.setText("");
        NetSalarytxt.setText("");
    }

    private void generateslipNo() {
          try {
             paySlipNotxt.setText(IDGenerator.getNewID("SalaryDetails","sdId","P"));
         } catch (SQLException ex) {
             Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
         }
         
    }

    private void generatesalId() {
         try {
             salIdtxt.setText(IDGenerator.getNewID("salary","salId","S"));
         } catch (SQLException ex) {
             Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(paySlip.class.getName()).log(Level.SEVERE, null, ex);
         }
         
    }
    }
    

